space: {{ isaSchemaSpace }}
externalId: ProductSegment
name: ProductSegment
description: Segment of the product process and resources (ISA-95 Level 3)
implements:
- space: cdf_cdm
  externalId: CogniteDescribable
  version: v1
  type: view
version: {{ viewVersion }}
properties:
  product_segment_id:
    container:
      space: {{ isaSchemaSpace }}
      externalId: ProductSegment
      type: container
    containerPropertyIdentifier: product_segment_id
    name: Product Segment ID
    description: >
      Unique identifier for the product segment entity, conforming to ISA-95 Level 3 product 
      segment standards. A product segment represents a segment for product activities 
      and resource allocation. The product_segment_id serves as the primary key and enables 
      consistent tracking across all manufacturing operations, from segment creation through 
      execution to completion. This identifier should align with product planning systems and 
      support integration with product planning and resource management platforms. [ISA-95 Level 3]
  set_points:
    container:
      space: {{ isaSchemaSpace }}
      externalId: ProductSegment
      type: container
    containerPropertyIdentifier: set_points
    name: Set Points
    description: >
      Set points for the product segment, typically describing the set points's purpose 
      or time period (e.g., "100%", "50%", "25%"). The set points follows ISA-95 Level 3 naming conventions and should be 
      descriptive enough for product planners and operators to identify the set points's purpose. 
      This set points is often used in product planning systems, scheduling displays, and operational 
      documentation. [ISA-95 Level 3]
  time_requirements:
    container:
      space: {{ isaSchemaSpace }}
      externalId: ProductSegment
      type: container
    containerPropertyIdentifier: time_requirements
    name: Time Requirements
    description: >
      Time requirements for the product segment, typically describing the time requirements's purpose 
      or time period (e.g., "10 minutes", "30 minutes", "1 hour"). The time requirements follows ISA-95 Level 3 naming conventions and should be 
      descriptive enough for product planners and operators to identify the time requirements's purpose. 
      This time requirements is often used in product planning systems, scheduling displays, and operational 
      documentation. [ISA-95 Level 3]
  temperature_requirements:
    container:
      space: {{ isaSchemaSpace }}
      externalId: ProductSegment
      type: container
    containerPropertyIdentifier: temperature_requirements
    name: Temperature Requirements
    description: >
      Temperature requirements for the product segment, typically describing the temperature requirements's purpose 
      or time period (e.g., "100°C", "200°C", "300°C"). The temperature requirements follows ISA-95 Level 3 naming conventions and should be 
      descriptive enough for product planners and operators to identify the temperature requirements's purpose. 
      This temperature requirements is often used in product planning systems, scheduling displays, and operational 
      documentation. [ISA-95 Level 3]
  flow_rate_requirements:
    container:
      space: {{ isaSchemaSpace }}
      externalId: ProductSegment
      type: container
    containerPropertyIdentifier: flow_rate_requirements
    name: Flow Rate Requirements
    description: >
      Flow rate requirements for the product segment, typically describing the flow rate requirements's purpose 
      or time period (e.g., "100 L/h", "200 L/h", "300 L/h"). The flow rate requirements follows ISA-95 Level 3 naming conventions and should be 
      descriptive enough for product planners and operators to identify the flow rate requirements's purpose. 
      This flow rate requirements is often used in product planning systems, scheduling displays, and operational 
      documentation. [ISA-95 Level 3]
  pressure_requirements:
    container:
      space: {{ isaSchemaSpace }}
      externalId: ProductSegment
      type: container
    containerPropertyIdentifier: pressure_requirements
    name: Pressure Requirements
    description: >
      Pressure requirements for the product segment, typically describing the pressure requirements's purpose 
      or time period (e.g., "100 kPa", "200 kPa", "300 kPa"). The pressure requirements follows ISA-95 Level 3 naming conventions and should be 
      descriptive enough for product planners and operators to identify the pressure requirements's purpose. 
      This pressure requirements is often used in product planning systems, scheduling displays, and operational 
      documentation. [ISA-95 Level 3]
  ph_requirements:
    container:
      space: {{ isaSchemaSpace }}
      externalId: ProductSegment
      type: container
    containerPropertyIdentifier: ph_requirements
    name: Ph Requirements
    description: >
      Ph requirements for the product segment, typically describing the ph requirements's purpose 
      or time period (e.g., "100 pH", "200 pH", "300 pH"). The ph requirements follows ISA-95 Level 3 naming conventions and should be 
      descriptive enough for product planners and operators to identify the ph requirements's purpose. 
      This ph requirements is often used in product planning systems, scheduling displays, and operational 
      documentation. [ISA-95 Level 3]
  status:
    container:
      space: {{ isaSchemaSpace }}
      externalId: ProductSegment
      type: container
    containerPropertyIdentifier: status
    name: Status
    description: >
      Status of the product segment, typically describing the status's purpose 
      or time period (e.g., "Draft", "Approved", "Active", "On Hold", "Completed", 
      "Cancelled", "Archived"). The status follows ISA-95 Level 3 naming conventions and should be 
      descriptive enough for product planners and operators to identify the status's purpose. 
      This status is often used in product planning systems, scheduling displays, and operational 
      documentation. [ISA-95 Level 3]
  valid_from:
    container:
      space: {{ isaSchemaSpace }}
      externalId: ProductSegment
      type: container
    containerPropertyIdentifier: valid_from
    name: Valid From
    description: >
      Timestamp indicating when the product segment is valid from, enabling 
      time-based product scheduling and resource allocation. The valid_from, combined 
      with valid_to, enables calculation of product segment duration, capacity utilization, 
      and product segment adherence metrics. This timestamp is critical for product planning 
      and schedule optimization. [ISA-95 Level 3]
  valid_to:
    container:
      space: {{ isaSchemaSpace }}
      externalId: ProductSegment
      type: container
    containerPropertyIdentifier: valid_to
    name: Valid To
    description: >
      Timestamp indicating when the product segment is valid to, enabling 
      time-based product scheduling and resource allocation. The valid_to, combined 
      with valid_from, enables calculation of product segment duration, capacity utilization, 
      and product segment adherence metrics. This timestamp is critical for product planning 
      and schedule optimization. [ISA-95 Level 3]
  composition_requirements:
    container:
      space: {{ isaSchemaSpace }}
      externalId: ProductSegment
      type: container
    containerPropertyIdentifier: composition_requirements
    name: Composition Requirements
    description: >
      Composition requirements for the product segment, typically describing the composition requirements's purpose 
      or time period (e.g., "100%", "50%", "25%"). The composition requirements follows ISA-95 Level 3 naming conventions and should be 
      descriptive enough for product planners and operators to identify the composition requirements's purpose. 
      This composition requirements is often used in product planning systems, scheduling displays, and operational 
      documentation. [ISA-95 Level 3]
  timeSeries:
    container:
      space: {{ isaSchemaSpace }}
      externalId: ProductSegment
      type: container
    containerPropertyIdentifier: timeSeries
    name: Time Series
    description: >
      Time series for the product segment, typically describing the time series's purpose 
      or time period (e.g., "100%", "50%", "25%"). The time series follows ISA-95 Level 3 naming conventions and should be 
      descriptive enough for product planners and operators to identify the time series's purpose. 
      This time series is often used in product planning systems, scheduling displays, and operational 
      documentation. [ISA-95 Level 3]
    source:
      space: {{ isaSchemaSpace }}
      externalId: ISATimeSeries
      version: {{ viewVersion }}
      type: view
  material_requirements:
    container:
      space: {{ isaSchemaSpace }}
      externalId: ProductSegment
      type: container
    containerPropertyIdentifier: material_requirements
    name: Material Requirements
    description: >
      Material requirements for the product segment, typically describing the material requirements's purpose 
      or time period (e.g., "100%", "50%", "25%"). The material requirements follows ISA-95 Level 3 naming conventions and should be 
      descriptive enough for product planners and operators to identify the material requirements's purpose. 
      This material requirements is often used in product planning systems, scheduling displays, and operational 
      documentation. [ISA-95 Level 3] 
    source: 
      space: {{ isaSchemaSpace }}
      externalId: MaterialLot
      version: {{ viewVersion }}
      type: view
  equipment_requirements:
    container:
      space: {{ isaSchemaSpace }}
      externalId: ProductSegment
      type: container
    containerPropertyIdentifier: equipment_requirements
    name: Equipment Requirements
    description: >
      Equipment requirements for the product segment, typically describing the equipment requirements's purpose 
      or time period (e.g., "100%", "50%", "25%"). The equipment requirements follows ISA-95 Level 3 naming conventions and should be 
      descriptive enough for product planners and operators to identify the equipment requirements's purpose. 
      This equipment requirements is often used in product planning systems, scheduling displays, and operational 
      documentation. [ISA-95 Level 3]
    source:
      space: {{ isaSchemaSpace }}
      externalId: Equipment
      version: {{ viewVersion }}
      type: view
  process_parameters:
    source:
      space: {{ isaSchemaSpace }}
      externalId: ProcessParameter
      version: {{ viewVersion }}
      type: view
    through:
      source:
        space: {{ isaSchemaSpace }}
        externalId: ProcessParameter
        version: {{ viewVersion }}
        type: view
      identifier: product_segment
    name: Process Parameters
    description: >
      Reverse relationship collection of all ProcessParameter entities that are associated with this product segment. Process parameters 
      represent the process parameters that are used during the product segment execution. This relationship enables 
      navigation from product segment to process parameter level, supporting process parameter-level production planning analysis and 
      production tracking. This relationship is essential for ISA-95 Level 3 production tracking, where product segments are used to track process parameters. [ISA-95 Level 3]
    connectionType: multi_reverse_direct_relation
  files:
    container:
      space: {{ isaSchemaSpace }}
      externalId: ProductSegment
      type: container
    containerPropertyIdentifier: files
    name: Files
    description: >
      Collection of document files associated with this product segment, following ISA-95 Level 3 product 
      segment documentation standards. Files may include segment specifications, process procedures, 
      engineering drawings, certificates, and other product segment-related documentation. This relationship 
      enables comprehensive product segment documentation management and supports engineering, operations, 
      and production planning activities. Document organization should follow ISA-95 Level 3 document 
      classification and naming conventions. [ISA-95 Level 3]
    source:
      space: {{ isaSchemaSpace }}
      externalId: ISAFile
      version: {{ viewVersion }}
      type: view
  product_definition:
    source:
      space: {{ isaSchemaSpace }}
      externalId: ProductDefinition
      version: {{ viewVersion }}
      type: view
    through:
      source:
        space: {{ isaSchemaSpace }}
        externalId: ProductDefinition
        version: {{ viewVersion }}
        type: view
      identifier: product_segment
    name: Product Definition
    description: >
      Reverse relationship collection of all ProductDefinition entities that are associated with this product segment. 
      Product definitions represent the definition of the product process and resources. This relationship enables 
      product segment-to-product definition navigation, supporting product definition-level production planning analysis and 
      production tracking. This relationship is essential for understanding how product definitions are defined and executed within the product segment. [ISA-95 Level 3]
    connectionType: multi_reverse_direct_relation


