class FieldNames:
    # -- Camel Case Fields --
    EXTERNAL_ID_CAMEL_CASE = "externalId"
    CREATED_TIME_CAMEL_CASE = "createdTime"
    LAST_UPDATED_TIME_CAMEL_CASE = "lastUpdatedTime"
    FILE_EXTERNAL_ID_CAMEL_CASE = "fileExternalId"
    FILE_SPACE_CAMEL_CASE = "fileSpace"
    FILE_NAME_CAMEL_CASE = "fileName"
    FILE_SOURCE_ID_CAMEL_CASE = "fileSourceid"
    FILE_MIME_TYPE_CAMEL_CASE = "fileMimetype"
    SCHEMA_SPACE_CAMEL_CASE = "schemaSpace"
    VERSION_CAMEL_CASE = "version"
    INSTANCE_SPACE_CAMEL_CASE = "instanceSpace"
    ANNOTATION_STATE_VIEW_CAMEL_CASE = "annotationStateView"
    FILE_VIEW_CAMEL_CASE = "fileView"
    PAGE_COUNT_CAMEL_CASE = "pageCount"
    ANNOTATED_PAGE_COUNT_CAMEL_CASE = "annotatedPageCount"
    ANNOTATION_STATUS_CAMEL_CASE = "annotationStatus"
    ATTEMPT_COUNT_CAMEL_CASE = "attemptCount"
    LINKED_FILE_CAMEL_CASE = "linkedFile"
    PREPARE_FUNCTION_ID_CAMEL_CASE = "prepareFunctionId"
    PREPARE_FUNCTION_CALL_ID_CAMEL_CASE = "prepareFunctionCallId"
    LAUNCH_FUNCTION_ID_CAMEL_CASE = "launchFunctionId"
    LAUNCH_FUNCTION_CALL_ID_CAMEL_CASE = "launchFunctionCallId"
    FINALIZE_FUNCTION_ID_CAMEL_CASE = "finalizeFunctionId"
    FINALIZE_FUNCTION_CALL_ID_CAMEL_CASE = "finalizeFunctionCallId"
    PROMOTE_FUNCTION_ID_CAMEL_CASE = "promoteFunctionId"
    PROMOTE_FUNCTION_CALL_ID_CAMEL_CASE = "promoteFunctionCallId"
    DATA_MODEL_VIEWS_CAMEL_CASE = "dataModelViews"

    # -- Snake Case Fields --
    STATUS_LOWER_CASE = "status"
    TIME_BUCKET_SNAKE_CASE = "time_bucket"
    PREPARE_LOG_SNAKE_CASE = "prepare_log"
    LAUNCH_LOG_SNAKE_CASE = "launch_log"
    FINALIZE_LOG_SNAKE_CASE = "finalize_log"
    PROMOTE_LOG_SNAKE_CASE = "promote_log"
    TO_TEXT_SNAKE_CASE = "to_text"
    FUNCTION_ID_SNAKE_CASE = "function_id"
    CALL_ID_SNAKE_CASE = "call_id"

    # -- Title Case Fields --
    PREPARE_LOG_TITLE_CASE = "Prepare Log"
    LAUNCH_LOG_TITLE_CASE = "Launch Log"
    FINALIZE_LOG_TITLE_CASE = "Finalize Log"
    PROMOTE_LOG_TITLE_CASE = "Promote Log"
    SELECT_TITLE_CASE = "Select"
    LAUNCH_TITLE_CASE = "Launch"
    FINALIZE_TITLE_CASE = "Finalize"
    FILES_PROCESSED_TITLE_CASE = "Files Processed"
    SUCCESSFULL_RUNS_TITLE_CASE = "Successful Runs"
    FAILED_RUNS_TITLE_CASE = "Failed Runs"

    # -- Lower Case Fields --
    SPACE_LOWER_CASE = "space"
    TIMESTAMP_LOWER_CASE = "timestamp"
    COUNT_LOWER_CASE = "count"
    TYPE_LOWER_CASE = "type"
    TOTAL_LOWER_CASE = "total"
    SUCCESS_LOWER_CASE = "success"
    FAILED_LOWER_CASE = "failed"
    CALLER_LOWER_CASE = "caller"
    MESSAGE_LOWER_CASE = "message"
    FAILURE_LOWER_CASE = "failure"

    # -- Custom Case Fields --
