repos:
  # Local hooks
  - repo: local
    hooks:
      - id: validate-packages
        name: Validate packages.toml
        entry: python validate_packages.py
        language: system
        types: [toml]
        files: ^modules/packages\.toml$
        pass_filenames: false
        always_run: true
        description: "Validates the packages.toml file structure and module paths"
        
  # Standard Python formatting and linting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.0
    hooks:
      - id: ruff
        args: [--fix]
        exclude: ^modules/
      - id: ruff-format
        
  # Markdown linting
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.38.0
    hooks:
      - id: markdownlint
        args: [--fix, --config, .markdownlint.json]
        exclude: ^modules/
