environment:
  name: dev
  project: darren-core
  validation-type: dev
  selected:
  - modules/accelerators/contextualization/cdf_discovery
variables:
  modules:
    accelerators:
      contextualization:
        cdf_discovery:
          function_version: 1.0.0
          dataset: ds_discovery_etl
          function_client_id: ${IDP_CLIENT_ID}
          function_client_secret: ${IDP_CLIENT_SECRET}
          workflowClientId: ${IDP_CLIENT_ID}
          workflowClientSecret: ${IDP_CLIENT_SECRET}
          source_metadata_batch_size: 100
          source_metadata_batch_timeout: 60
          subscription_batch_size: 100
          subscription_batch_timeout: 60
          source_index_watermark_cron: 0 * * * *
          gp_asset_site_a_extractor: 6c4c04ac-054f-4653-b888-009581985246
          gp_asset_site_a_processing: 6c4c04ac-054f-4653-b888-009581985246
          gp_asset_site_a_read: 6c4c04ac-054f-4653-b888-009581985246


