[project]
name = "cdf-entity-matching"
version = "0.1.0"
description = ""
authors = [
    {name = "None"}
]
readme = "README.md"
requires-python = ">=3.12,<4.0"
dependencies = [
    "cognite-extractor-utils (>=7)",
    "cognite-sdk (==7.*)",
    "pytest (>=7.0.0)",
    "tenacity (>=8.0.0)",
    "psutil (>=5.9.0)",
    "cognite-toolkit (>=0.6.62,<0.7.0)",
    "dotenv (>=0.9.9,<0.10.0)",
    "python-certifi-win32 (>=1.6.1,<2.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
