name: discovery_etl
function_version: 1.0.0
organization: YourOrg
location_name: LOC
source_name: SOURCE
schema_space: cdf_cdm
view_version: v1
function_client_id: ${IDP_CLIENT_ID}
function_client_secret: ${IDP_CLIENT_SECRET}
workflow_schedule: '0 2 * * *'
dataset: ds_discovery_etl
workflow_definitions:
  registry: transform/workflow_definitions/registry.yaml
  instances_dir: transform/workflow_definitions/instances
  templates_dir: transform/workflow_definitions/templates
