class FieldNames:
    # -- Camel Case Fields --
    EXTERNAL_ID_CAMEL_CASE = "externalId"
    FILE_EXTERNAL_ID_CAMEL_CASE = "fileExternalId"
    SCHEMA_SPACE_CAMEL_CASE = "schemaSpace"
    VERSION_CAMEL_CASE = "version"
    INSTANCE_SPACE_CAMEL_CASE = "instanceSpace"
    DATA_MODEL_VIEWS_CAMEL_CASE = "dataModelViews"
    FILE_VIEW_CAMEL_CASE = "fileView"
    ASSET_VIEW_CAMEL_CASE = "targetEntityView"
    FINALIZE_FUNCTION_CAMEL_CASE = "finalizeFunction"
    LAUNCH_FUNCTION_CAMEL_CASE = "launchFunction"
    RAW_TABLES_CAMEL_CASE = "rawTables"
    RAW_DATABASE_CAMEL_CASE = "rawDb"
    RAW_TABLE_DOC_PATTERN_CAMEL_CASE = "rawTableDocPattern"
    RAW_TABLE_DOC_TAG_CAMEL_CASE = "rawTableDocTag"
    RAW_TABLE_DOC_DOC_CAMEL_CASE = "rawTableDocDoc"
    RAW_TABLE_CACHE_CAMEL_CASE = "rawTableCache"
    RAW_TABLE_MANUAL_PATTERNS_CATALOG_CAMEL_CASE = "rawManualPatternsCatalog"
    APPLY_SERVICE_CAMEL_CASE = "applyService"
    CACHE_SERVICE_CAMEL_CASE = "cacheService"
    START_NODE_RESOURCE_CAMEL_CASE = "startNodeResource"
    END_NODE_RESOURCE_CAMEL_CASE = "endNodeResource"
    START_NODE_TEXT_CAMEL_CASE = "startNodeText"
    START_NODE_CAMEL_CASE = "startNode"
    END_NODE_RESOURCE_TYPE_CAMEL_CASE = "endNodeResourceType"
    START_SOURCE_ID_CAMEL_CASE = "startSourceId"
    END_NODE_CAMEL_CASE = "endNode"
    END_NODE_SPACE_CAMEL_CASE = "endNodeSpace"
    IS_FROM_PATTERN_TABLE_CAMEL_CASE = "isFromPatternTable"
    SOURCE_ID_CAMEL_CASE = "sourceId"
    SECONDARY_SCOPE_PROPERTY_CAMEL_CASE = "secondaryScopeProperty"
    FILE_RESOURCE_PROPERTY_CAMEL_CASE = "fileResourceProperty"
    ASSET_RESOURCE_PROPERTY_CAMEL_CASE = "targetEntityResourceProperty"
    NORMALIZED_STATUS_CAMEL_CASE = "normalizedStatus"

    # -- Snake Case Fields --
    COVERAGE_PERCENTAGE_SNAKE_CASE = "coverage_pct"
    ACTUAL_COUNT_SNAKE_CASE = "actual_count"
    POTENTIAL_COUNT_SNAKE_CASE = "potential_count"
    TOTAL_POSSIBLE_SNAKE_CASE = "total_possible"
    RESOURCE_TYPE_SNAKE_CASE = "resource_type"
    PATTERN_SCOPE_SNAKE_CASE = "pattern_scope"
    ASSET_RESOURCE_PROPERTY_SNAKE_CASE = "asset_resource_property"
    FILE_RESOURCE_PROPERTY_SNAKE_CASE = "file_resource_property"
    SECONDARY_SCOPE_PROPERTY_SNAKE_CASE = "secondary_scope_property"
    RAW_TABLE_MANUAL_PATTERNS_CATALOG_SNAKE_CASE = "raw_manual_patterns_catalog"
    RAW_TABLE_PATTERN_CACHE_SNAKE_CASE = "raw_table_pattern_cache"
    RAW_TABLE_FILE_TAGS_SNAKE_CASE = "raw_table_file_tags"
    RAW_TABLE_ASSET_TAGS_SNAKE_CASE = "raw_table_asset_tags"
    RAW_TABLE_PATTERN_TAGS_SNAKE_CASE = "raw_table_pattern_tags"
    RAW_DB_SNAKE_CASE = "raw_db"
    CACHE_SERVICE_SNAKE_CASE = "cache_service"
    APPLY_SERVICE_SNAKE_CASE = "apply_service"
    ANNOTATION_TYPE_SNAKE_CASE = "annotation_type"
    CREATED_BY_SNAKE_CASE = "created_by"
    ENTITY_TYPE_SNAKE_CASE = "entity_type"
    EDITED_ROWS_SNAKE_CASE = "edited_rows"
    ADDED_ROWS_SNAKE_CASE = "added_rows"
    DELETED_ROWS_SNAKE_CASE = "deleted_rows"

    # -- Title Case Fields --
    SELECT_TITLE_CASE = "Select"
    TAG_TITLE_CASE = "Tag"
    STATUS_TITLE_CASE = "Status"
    NAME_TITLE_CASE = "Name"
    RESOURCE_TYPE_TITLE_CASE = "Resource Type"
    SECONDARY_SCOPE_TITLE_CASE = "Secondary Scope"
    PATTERN_SCOPE_TITLE_CASE = "Pattern Scope"
    ACTUAL_ANNOTATIONS_TITLE_CASE = "Actual Annotations"
    POTENTIAL_ANNOTATIONS_TITLE_CASE = "Potential Annotations"
    TOTAL_ANNOTATIONS_TITLE_CASE = "Total Annotations Considered"
    COVERAGE_TITLE_CASE = "Coverage (%)"
    OVERALL_COVERAGE_TITLE_CASE = "Overall Coverage (%)"
    FILE_RESOURCE_PROPERTY_TITLE_CASE = "File Resource Property"
    TAG_ENTITY_RESOURCE_TYPE_TITLE_CASE = "Tag Entity Resource Type"
    OCCURRENCES_TITLE_CASE = "Occurrences"
    ASSOCIATED_FILES_TITLE_CASE = "Associated Files"
    ALL_TITLE_CASE = "All"
    EXTERNAL_ID_TITLE_CASE = "External ID"
    SOURCE_ID_TITLE_CASE = "Source ID"
    ENTITY_TYPE_TITLE_CASE = "Entity Type"
    FILE_TITLE_CASE = "File"
    ASSET_TITLE_CASE = "Asset"
    PATTERN_TITLE_CASE = "Pattern"

    # -- Lower Case Fields --
    STATUS_LOWER_CASE = "status"
    NAME_LOWER_CASE = "name"
    TAGS_LOWER_CASE = "tags"
    ACTUAL_LOWER_CASE = "actual"
    POTENTIAL_LOWER_CASE = "potential"
    STREAMLIT_LOWER_CASE = "streamlit"
    PATTERNS_LOWER_CASE = "patterns"
    SAMPLE_LOWER_CASE = "sample"


    # -- Pascal Case Fields --
    PROMOTED_AUTO_PASCAL_CASE = "PromotedAuto"
    PROMOTE_ATTEMPTED_PASCAL_CASE = "PromoteAttempted"
    AMBIGUOUS_MATCH_PASCAL_CASE = "AmbiguousMatch"
    FILE_PATTERN_SAMPLES_PASCAL_CASE = "FilePatternSamples"
    ASSET_PATTERN_SAMPLES_PASCAL_CASE = "AssetPatternSamples"

    # -- Custom Case Fields --
    DIAGRAMS_ASSET_LINK_CUSTOM_CASE = "diagrams.AssetLink"
    DIAGRAMS_FILE_LINK_CUSTOM_CASE = "diagrams.FileLink"
