externalId: 'ep_ctx_metadata_update'
config:
  parameters:
    debug: False
    debugFile: 'PH-ME-P-0156-001.pdf'
    runAll: False
    rawDb: 'ds_files_{{location_name}}_{{source_name}}'
    rawTableState: 'files_state_store'
  data:
    job:
      fileView:
        schemaSpace: {{ schemaSpace }}
        instanceSpace: {{ fileInstanceSpace }}
        externalId: {{organization}}File
        version: {{ viewVersion }}
      assetView:
        schemaSpace: {{ schemaSpace }}
        instanceSpace: {{ assetInstanceSpace }}
        externalId: {{organization}}Asset
        version: {{ viewVersion }}