config:
  source_views:
    - view_external_id: "txEquipment"
      view_space: "sp_enterprise_process_industry"
      view_version: "v1"
      entity_type: "asset"
      batch_size: 100
      filter:
        equals:
          property: [ "node", "type" ]
          value: "Equipment"
      include_properties:
        - "name"
        - "description"
        - "tagIds"
        - "equipmentType"
        - "specifications"
  extraction_rules:
    - name: "flow_control_valve"
      source_fields:
        - field_name: "name"
          field_type: "string"
          required: true
          max_length: 500
      method: "regex"
      pattern: '\b[A-Z]{2,3}V[-_]?\d{2,4}[A-Z]?\b'
      regex_options:
        multiline: false
        dotall: false
        ignore_case: false
        unicode: true
      validation_pattern: '^[A-Z]{2,3}V\d{2,4}[A-Z]?$'  # Post-extraction validation
