externalId: 'ctx_key_extraction_regex'
config:
  parameters:
    debug: true
    run_all: true
    remove_old_keys: true
    raw_db: bingus
    raw_table_state: bingus
    raw_table_key: bingus
  data:
    source_views:
      - view_external_id: "txEquipment"
        view_space: "sp_enterprise_process_industry"
        view_version: "v1"
        entity_type: "asset"
        batch_size: 100
        filters:
          - operator: EQUALS
            target_property: "name"
            values: "Bingus"
        include_properties:
          - "name"
          - "description"
          - "tagIds"
          - "equipmentType"
          - "specifications"
    extraction_rules:
      - rule_id: "1"
        method: "regex"
        parameters:
          name: "flow_control_valve"
          pattern: '\b[A-Z]{2,3}V[-_]?\d{2,4}[A-Z]?\b'
          regex_options:
            multiline: false
            dotall: false
            ignore_case: false
            unicode: true
          validation_pattern: '^[A-Z]{2,3}V\d{2,4}[A-Z]?$'  # Post-extraction validation
          source_fields:
            - field_name: "name"
              field_type: "string"
              required: true
              max_length: 500
              seperator: ','
              priority: 1
              role: "target"
              preprocessing:
                - 'trim'
                - 'lowercase'
    field_selection_strategy: 'first_match'