[module]
title = "SAP Source System Events"
id = "dp:acc:src:sap_events"
package_id = "dp:accelerators"

[[data]]
repoType = "http"
repo = "https://apps-cdn.cogniteapp.com/toolkit/publicdata"
source = "workitem.Table.csv;workorder.Table.csv;workpackage.Table.csv;worktask.Table.csv"
destination = "raw/"

[[extra_resources]]
location = "accelerators/cdf_common/data_sets/demo.DataSet.yaml"

[[extra_resources]]
location = "accelerators/cdf_common/data_models/demo.Space.yaml"

[[extra_resources]]
location = "accelerators/cdf_common/raw/source.DataBase.yaml"

[[extra_resources]]
location = "data_models/cdf_process_industry_extension/data_models"
