"""Public facade for ETL transform stage (handler registry + row pipeline)."""

from __future__ import annotations

from cdf_fn_common.etl_transform.transform_handlers import (
    ASSET_TAG_FROM_NAME_REGEX,
    CORE_TRANSFORM_HANDLERS,
    ELT_TRANSFORM_HANDLERS,
    TRANSFORM_HANDLERS,
    V1_TRANSFORM_HANDLERS,
    TransformResult,
    TransformScalar,
    apply_change_case,
    apply_coerce_scalar,
    apply_default_if_empty,
    apply_format_datetime,
    apply_hash_stable,
    apply_heuristic_sampler,
    apply_leading_zero_normalize,
    apply_mask_string,
    apply_output_template,
    apply_parse_json_extract,
    apply_regex_substitution,
    apply_sequential_literal_replace,
    apply_split_join,
    apply_split_string,
    apply_static_lookup_map,
    apply_substitution_variants,
    apply_transform_handler,
    apply_trim_whitespace,
    extract_field_values,
    resolve_handler_block,
    resolve_handler_id,
    transform_row_properties,
    validate_transform_config,
    write_output_to_props,
)
from cdf_fn_common.etl_transform.transform_steps import (
    apply_transform_steps_to_props,
    validate_transform_pipeline_config,
)

__all__ = [
    "ASSET_TAG_FROM_NAME_REGEX",
    "CORE_TRANSFORM_HANDLERS",
    "ELT_TRANSFORM_HANDLERS",
    "TRANSFORM_HANDLERS",
    "V1_TRANSFORM_HANDLERS",
    "TransformResult",
    "TransformScalar",
    "apply_change_case",
    "apply_coerce_scalar",
    "apply_default_if_empty",
    "apply_format_datetime",
    "apply_hash_stable",
    "apply_heuristic_sampler",
    "apply_leading_zero_normalize",
    "apply_mask_string",
    "apply_output_template",
    "apply_parse_json_extract",
    "apply_regex_substitution",
    "apply_sequential_literal_replace",
    "apply_split_join",
    "apply_split_string",
    "apply_static_lookup_map",
    "apply_substitution_variants",
    "apply_transform_handler",
    "apply_transform_steps_to_props",
    "apply_trim_whitespace",
    "extract_field_values",
    "resolve_handler_block",
    "resolve_handler_id",
    "transform_row_properties",
    "validate_transform_config",
    "validate_transform_pipeline_config",
    "write_output_to_props",
]
