"""Tests for the uv workspace and deploy requirements export."""

from __future__ import annotations

import json
from pathlib import Path

from scripts.export_deploy_requirements import EXPORT_TARGETS

REPO_ROOT = Path(__file__).resolve().parents[1]


def test_export_targets_have_pyproject_and_requirements() -> None:
    for rel_path in EXPORT_TARGETS:
        package_dir = REPO_ROOT / rel_path
        assert (package_dir / "pyproject.toml").is_file(), rel_path
        requirements = package_dir / "requirements.txt"
        assert requirements.is_file(), rel_path
        content = requirements.read_text(encoding="utf-8")
        assert content.startswith("# This file was autogenerated by uv"), rel_path


def test_workspace_members_include_export_targets() -> None:
    manifest = json.loads((REPO_ROOT / "scripts" / "uv_workspace_members.json").read_text(encoding="utf-8"))
    for rel_path in EXPORT_TARGETS:
        assert rel_path in manifest
