dataset: ingestion
instanceSpace: inst_cfihos_oil_and_gas
directRelationJob: ctx_files_direct_relation_write
rawSourceDatabase: ingestion
rawStateDatabase: contextualizationState
rawStateTable: diagramParsing
schemaSpace: cdf_cdm
annotationSpace: inst_cfihos_oil_and_gas
functionSpace: springfield_functions
