space: {{ isaSchemaSpace }}
externalId: ISA_Manufacturing_SLM
name: ISA Manufacturing Data Model SLM
description: ISA-95/88 based manufacturing domain model, aggregating all ISA views in the ISA Manufacturing domain. This is the Solution Level Model (SLM) for the ISA Manufacturing domain, only including ISA-specific views.
version: {{ viewVersion }}
views:
- space: {{ isaSchemaSpace }}
  externalId: ISAAsset
  version: {{ viewVersion }}
  type: view
- space: {{ isaSchemaSpace }}
  externalId: Area
  version: {{ viewVersion }}
  type: view
- space: {{ isaSchemaSpace }}
  externalId: Batch
  version: {{ viewVersion }}
  type: view
- space: {{ isaSchemaSpace }}
  externalId: ControlModule
  version: {{ viewVersion }}
  type: view
- space: {{ isaSchemaSpace }}
  externalId: Enterprise
  version: {{ viewVersion }}
  type: view
- space: {{ isaSchemaSpace }}
  externalId: Equipment
  version: {{ viewVersion }}
  type: view
- space: {{ isaSchemaSpace }}
  externalId: EquipmentModule
  version: {{ viewVersion }}
  type: view
- space: {{ isaSchemaSpace }}
  externalId: ProcessParameter
  version: {{ viewVersion }}
  type: view
- space: {{ isaSchemaSpace }}
  externalId: Operation
  version: {{ viewVersion }}
  type: view
- space: {{ isaSchemaSpace }}
  externalId: Phase
  version: {{ viewVersion }}
  type: view
- space: {{ isaSchemaSpace }}
  externalId: Procedure
  version: {{ viewVersion }}
  type: view
- space: {{ isaSchemaSpace }}
  externalId: ProcessCell
  version: {{ viewVersion }}
  type: view
- space: {{ isaSchemaSpace }}
  externalId: QualityResult
  version: {{ viewVersion }}
  type: view
- space: {{ isaSchemaSpace }}
  externalId: Recipe
  version: {{ viewVersion }}
  type: view
- space: {{ isaSchemaSpace }}
  externalId: Site
  version: {{ viewVersion }}
  type: view
- space: {{ isaSchemaSpace }}
  externalId: Unit
  version: {{ viewVersion }}
  type: view
- space: {{ isaSchemaSpace }}
  externalId: UnitProcedure
  version: {{ viewVersion }}
  type: view
- space: {{ isaSchemaSpace }}
  externalId: WorkOrder
  version: {{ viewVersion }}
  type: view
- space: {{ isaSchemaSpace }}
  externalId: ProductRequest
  version: {{ viewVersion }}
  type: view
- space: {{ isaSchemaSpace }}
  externalId: ProductDefinition
  version: {{ viewVersion }}
  type: view
- space: {{ isaSchemaSpace }}
  externalId: ProductSegment
  version: {{ viewVersion }}
  type: view
- space: {{ isaSchemaSpace }}
  externalId: Material
  version: {{ viewVersion }}
  type: view
- space: {{ isaSchemaSpace }}
  externalId: MaterialLot
  version: {{ viewVersion }}
  type: view
- space: {{ isaSchemaSpace }}
  externalId: Personnel
  version: {{ viewVersion }}
  type: view
- space: {{ isaSchemaSpace }}
  externalId: ISAFile
  version: {{ viewVersion }}
  type: view
- space: {{ isaSchemaSpace }}
  externalId: ISATimeSeries
  version: {{ viewVersion }}
  type: view
