space: {{ isaSchemaSpace }}
externalId: ISA_Manufacturing
name: ISA Manufacturing Data Model
description: ISA-95/88 based manufacturing domain model, aggregating all ISA. This is the Enterprise Data Model (EDM) for the ISA Manufacturing domain, including all views and interfaces.
version: {{ viewVersion }}
views:

# List of Cognite views used as Interfaces in DM

- space: cdf_cdm
  externalId: CogniteDescribable
  version: v1
  type: view
- space: cdf_cdm
  externalId: CogniteSourceable
  version: v1
  type: view
- space: cdf_cdm
  externalId: CogniteSourceSystem
  version: v1
  type: view
- space: cdf_cdm
  externalId: CogniteSchedulable
  version: v1
  type: view
- space: cdf_cdm
  externalId: CogniteVisualizable
  version: v1
  type: view
- space: cdf_cdm
  externalId: CogniteAsset
  version: v1
  type: view
- space: cdf_cdm
  externalId: CogniteAssetClass
  version: v1
  type: view
- space: cdf_cdm
  externalId: CogniteAssetType
  version: v1
  type: view
- space: cdf_cdm
  externalId: CogniteEquipment
  version: v1
  type: view
- space: cdf_cdm
  externalId: CogniteEquipmentType
  version: v1
  type: view
- space: cdf_cdm
  externalId: CogniteFile
  version: v1
  type: view
- space: cdf_cdm
  externalId: CogniteFileCategory
  version: v1
  type: view
- space: cdf_cdm
  externalId: CogniteActivity
  version: v1
  type: view
- space: cdf_cdm
  externalId: CogniteTimeSeries
  version: v1
  type: view
- space: cdf_cdm
  externalId: CogniteAnnotation
  version: v1
  type: view
- space: cdf_cdm
  externalId: CogniteDiagramAnnotation
  version: v1
  type: view
- space: cdf_cdm
  externalId: CogniteUnit
  version: v1
  type: view
- space: cdf_cdm
  externalId: Cognite3DTransformation
  version: v1
  type: view
- space: cdf_cdm
  externalId: CogniteCubeMap
  version: v1
  type: view
- space: cdf_cdm
  externalId: Cognite3DObject
  version: v1
  type: view
- space: cdf_cdm
  externalId: Cognite3DModel
  version: v1
  type: view
- space: cdf_cdm
  externalId: CogniteCADModel
  version: v1
  type: view
- space: cdf_cdm
  externalId: Cognite3DRevision
  version: v1
  type: view
- space: cdf_cdm
  externalId: CognitePointCloudModel
  version: v1
  type: view
- space: cdf_cdm
  externalId: Cognite360ImageModel
  version: v1
  type: view
- space: cdf_cdm
  externalId: CogniteCADRevision
  version: v1
  type: view
- space: cdf_cdm
  externalId: CognitePointCloudRevision
  version: v1
  type: view
- space: cdf_cdm
  externalId: Cognite360ImageCollection
  version: v1
  type: view
- space: cdf_cdm
  externalId: CogniteCADNode
  version: v1
  type: view
- space: cdf_cdm
  externalId: CognitePointCloudVolume
  version: v1
  type: view
- space: cdf_cdm
  externalId: Cognite360Image
  version: v1
  type: view
- space: cdf_cdm
  externalId: Cognite360ImageStation
  version: v1
  type: view
- space: cdf_cdm
  externalId: Cognite360ImageAnnotation
  version: v1
  type: view

# List of Cognite views in extended DM

- space: {{ isaSchemaSpace }}
  externalId: ISAAsset
  version: {{ viewVersion }}
  type: view
- space: {{ isaSchemaSpace }}
  externalId: Area
  version: {{ viewVersion }}
  type: view
- space: {{ isaSchemaSpace }}
  externalId: Batch
  version: {{ viewVersion }}
  type: view
- space: {{ isaSchemaSpace }}
  externalId: ControlModule
  version: {{ viewVersion }}
  type: view
- space: {{ isaSchemaSpace }}
  externalId: Enterprise
  version: {{ viewVersion }}
  type: view
- space: {{ isaSchemaSpace }}
  externalId: Equipment
  version: {{ viewVersion }}
  type: view
- space: {{ isaSchemaSpace }}
  externalId: EquipmentModule
  version: {{ viewVersion }}
  type: view
- space: {{ isaSchemaSpace }}
  externalId: ProcessParameter
  version: {{ viewVersion }}
  type: view
- space: {{ isaSchemaSpace }}
  externalId: Operation
  version: {{ viewVersion }}
  type: view
- space: {{ isaSchemaSpace }}
  externalId: Phase
  version: {{ viewVersion }}
  type: view
- space: {{ isaSchemaSpace }}
  externalId: Procedure
  version: {{ viewVersion }}
  type: view
- space: {{ isaSchemaSpace }}
  externalId: ProcessCell
  version: {{ viewVersion }}
  type: view
- space: {{ isaSchemaSpace }}
  externalId: QualityResult
  version: {{ viewVersion }}
  type: view
- space: {{ isaSchemaSpace }}
  externalId: Recipe
  version: {{ viewVersion }}
  type: view
- space: {{ isaSchemaSpace }}
  externalId: Site
  version: {{ viewVersion }}
  type: view
- space: {{ isaSchemaSpace }}
  externalId: Unit
  version: {{ viewVersion }}
  type: view
- space: {{ isaSchemaSpace }}
  externalId: UnitProcedure
  version: {{ viewVersion }}
  type: view
- space: {{ isaSchemaSpace }}
  externalId: WorkOrder
  version: {{ viewVersion }}
  type: view
- space: {{ isaSchemaSpace }}
  externalId: ProductRequest
  version: {{ viewVersion }}
  type: view
- space: {{ isaSchemaSpace }}
  externalId: ProductDefinition
  version: {{ viewVersion }}
  type: view
- space: {{ isaSchemaSpace }}
  externalId: ProductSegment
  version: {{ viewVersion }}
  type: view
- space: {{ isaSchemaSpace }}
  externalId: Material
  version: {{ viewVersion }}
  type: view
- space: {{ isaSchemaSpace }}
  externalId: MaterialLot
  version: {{ viewVersion }}
  type: view
- space: {{ isaSchemaSpace }}
  externalId: Personnel
  version: {{ viewVersion }}
  type: view
- space: {{ isaSchemaSpace }}
  externalId: ISAFile
  version: {{ viewVersion }}
  type: view
- space: {{ isaSchemaSpace }}
  externalId: ISATimeSeries
  version: {{ viewVersion }}
  type: view
