import {
  DiscoveryAliasPersistenceNode,
  DiscoveryClassicQueryNode,
  DiscoverySqlQueryNode,
  DiscoveryClassicSaveNode,
  DiscoveryInstanceFilterNode,
  DiscoveryConfidenceFilterNode,
  DiscoveryValidateNode,
  DiscoveryEndNode,
  DiscoveryInvertedIndexNode,
  DiscoveryJoinNode,
  DiscoveryMergeNode,
  DiscoveryRawQueryNode,
  DiscoveryRawSaveNode,
  DiscoverySourceViewNode,
  DiscoveryStartNode,
  DiscoverySubflowGraphInNode,
  DiscoverySubflowGraphOutNode,
  DiscoverySubgraphNode,
  DiscoveryTransformNode,
  DiscoveryValidationRuleNode,
  DiscoveryViewQueryNode,
  DiscoveryViewSaveNode,
} from "./discoveryNodes";

export const DISCOVERY_FLOW_NODE_TYPES = {
  discoverySubgraph: DiscoverySubgraphNode,
  discoverySubflowGraphIn: DiscoverySubflowGraphInNode,
  discoverySubflowGraphOut: DiscoverySubflowGraphOutNode,
  discoveryStart: DiscoveryStartNode,
  discoveryEnd: DiscoveryEndNode,
  discoverySourceView: DiscoverySourceViewNode,
  discoveryInstanceFilter: DiscoveryInstanceFilterNode,
  discoveryConfidenceFilter: DiscoveryConfidenceFilterNode,
  discoveryValidate: DiscoveryValidateNode,
  discoveryViewQuery: DiscoveryViewQueryNode,
  discoveryRawQuery: DiscoveryRawQueryNode,
  discoveryClassicQuery: DiscoveryClassicQueryNode,
  discoverySqlQuery: DiscoverySqlQueryNode,
  discoveryTransform: DiscoveryTransformNode,
  discoveryMerge: DiscoveryMergeNode,
  discoveryJoin: DiscoveryJoinNode,
  discoveryViewSave: DiscoveryViewSaveNode,
  discoveryRawSave: DiscoveryRawSaveNode,
  discoveryClassicSave: DiscoveryClassicSaveNode,
  discoveryMatchValidationRuleSourceView: DiscoveryValidationRuleNode,
  discoveryMatchValidationRuleExtraction: DiscoveryValidationRuleNode,
  discoveryMatchValidationRuleAliasing: DiscoveryValidationRuleNode,
  discoveryAliasPersistence: DiscoveryAliasPersistenceNode,
  discoveryInvertedIndex: DiscoveryInvertedIndexNode,
};
