import {
  KeaAliasPersistenceNode,
  KeaClassicQueryNode,
  KeaClassicSaveNode,
  KeaDiscoveryInstanceFilterNode,
  KeaDiscoveryConfidenceFilterNode,
  KeaDiscoveryValidateNode,
  KeaEndNode,
  KeaInvertedIndexNode,
  KeaJoinNode,
  KeaMergeNode,
  KeaRawQueryNode,
  KeaRawSaveNode,
  KeaSourceViewNode,
  KeaStartNode,
  KeaSubflowGraphInNode,
  KeaSubflowGraphOutNode,
  KeaSubgraphNode,
  KeaTransformNode,
  KeaValidationRuleNode,
  KeaViewQueryNode,
  KeaViewSaveNode,
} from "./keaNodes";

export const KEA_FLOW_NODE_TYPES = {
  keaSubgraph: KeaSubgraphNode,
  keaSubflowGraphIn: KeaSubflowGraphInNode,
  keaSubflowGraphOut: KeaSubflowGraphOutNode,
  keaStart: KeaStartNode,
  keaEnd: KeaEndNode,
  keaSourceView: KeaSourceViewNode,
  keaDiscoveryInstanceFilter: KeaDiscoveryInstanceFilterNode,
  keaDiscoveryConfidenceFilter: KeaDiscoveryConfidenceFilterNode,
  keaDiscoveryValidate: KeaDiscoveryValidateNode,
  keaViewQuery: KeaViewQueryNode,
  keaRawQuery: KeaRawQueryNode,
  keaClassicQuery: KeaClassicQueryNode,
  keaTransform: KeaTransformNode,
  keaMerge: KeaMergeNode,
  keaJoin: KeaJoinNode,
  keaViewSave: KeaViewSaveNode,
  keaRawSave: KeaRawSaveNode,
  keaClassicSave: KeaClassicSaveNode,
  keaMatchValidationRuleSourceView: KeaValidationRuleNode,
  keaMatchValidationRuleExtraction: KeaValidationRuleNode,
  keaMatchValidationRuleAliasing: KeaValidationRuleNode,
  keaAliasPersistence: KeaAliasPersistenceNode,
  keaInvertedIndex: KeaInvertedIndexNode,
};
