"""Emit one schedule ``*.WorkflowTrigger.yaml`` per leaf under ``workflows/<suffix>/``."""

from __future__ import annotations

import logging
from copy import deepcopy
from pathlib import Path
from typing import List, Sequence, Tuple

import yaml

from scope_build.context import ScopeBuildContext
from scope_build.paths import WORKFLOW_ARTIFACTS_REL, WORKFLOW_TEMPLATE_REL
from scope_build.io_util import strip_leading_comments_and_blanks
from scope_build.mode import scoped_workflow_external_id
from scope_build.naming import cdf_external_id_suffix
from scope_build.scope_document_limits import (
    MAX_SCOPE_DOCUMENT_JSON_BYTES,
    assert_scope_document_within_limit,
    assert_workflow_trigger_input_within_limit,
    minified_json_utf8_length,
)
from scope_build.scope_document_load import load_scope_document_dict_for_build
from scope_build.scope_document_patch import (
    prepare_scope_document_for_context,
    scope_configuration_for_workflow_trigger,
)
from scope_build.scope_yaml_io import dump_scope_document_yaml_roundtrip

logger = logging.getLogger(__name__)

# Legacy monolithic output (removed when running build).
LEGACY_MONOLITHIC_NAME = "key_extraction_aliasing_scope_triggers.WorkflowTrigger.yaml"

PLACEHOLDER = "__KEA_CDF_SUFFIX__"
DEFAULT_TRIGGER_TEMPLATE_REL = (
    WORKFLOW_TEMPLATE_REL / "workflow.template.WorkflowTrigger.yaml"
)
DEFAULT_SCOPE_DOCUMENT_REL = WORKFLOW_TEMPLATE_REL / "workflow.template.config.yaml"


def workflow_trigger_filename(workflow_base: str, suffix: str) -> str:
    """Basename for one schedule trigger (suffix from ``cdf_external_id_suffix``)."""
    return f"{workflow_base}.{suffix}.WorkflowTrigger.yaml"


def trigger_output_path(
    *,
    workflows_dir: Path,
    workflow_base: str,
    suffix: str,
) -> Path:
    """Directory + basename for a leaf trigger (scoped layout)."""
    name = workflow_trigger_filename(workflow_base, suffix)
    return workflows_dir / suffix / name


def scope_config_filename(workflow_base: str, suffix: str) -> str:
    """Basename for the leaf full unified scope YAML (operator / UI source of truth)."""
    return f"{workflow_base}.{suffix}.config.yaml"


def scope_config_document_path(
    *,
    workflows_dir: Path,
    workflow_base: str,
    suffix: str,
) -> Path:
    """Path to ``*.config.yaml`` alongside the sibling WorkflowTrigger for this leaf."""
    return workflows_dir / suffix / scope_config_filename(workflow_base, suffix)


SCOPE_CONFIG_HEADER = (
    "# Full unified scope for this leaf (source of truth for editing).\n"
    "# Trimmed copy is embedded under input.configuration in the sibling *.WorkflowTrigger.yaml.\n"
    "# Generated by scripts/build_scopes.py (workflow_triggers builder).\n"
)


def _write_scope_full_config_yaml(path: Path, scope_document: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    body = dump_scope_document_yaml_roundtrip(scope_document)
    path.write_text(SCOPE_CONFIG_HEADER + "\n" + body, encoding="utf-8")


def _cleanup_legacy_trigger_layout(workflows_dir: Path) -> None:
    """Remove superseded trigger layouts only (does not delete current dot-form per-scope files).

    Per-scope files ``<workflow_base>.<suffix>.WorkflowTrigger.yaml`` are always
    left on disk even when no longer in the configured ``scope_hierarchy.locations`` tree — remove those by hand if needed.
    """
    legacy = workflows_dir / LEGACY_MONOLITHIC_NAME
    if legacy.is_file():
        legacy.unlink()
        logger.info("Removed legacy monolithic triggers file %s", legacy)
    for pattern in (
        "key_extraction_aliasing_*.WorkflowTrigger.yaml",
        "cdf_discovery_aliasing_*.WorkflowTrigger.yaml",
    ):
        for p in sorted(workflows_dir.glob(pattern)):
            p.unlink()
            logger.info("Removed old-format trigger file %s", p.name)


class WorkflowTriggersBuilder:
    name = "workflow_triggers"

    def __init__(
        self,
        *,
        template_path: Path | None = None,
        scope_document_path: Path | None = None,
        workflow_base: str = "key_extraction_aliasing",
        overwrite: bool = False,
    ) -> None:
        self._template_path_override = template_path
        self._scope_document_path_override = scope_document_path
        self._workflow_base = workflow_base
        self._overwrite = overwrite

    def run(self, ctx: ScopeBuildContext) -> None:
        """Per-scope no-op; triggers are written in ``write_all``."""

    def write_all(
        self,
        contexts: Sequence[ScopeBuildContext],
        *,
        dry_run: bool,
        module_root: Path | None = None,
    ) -> list[Path] | None:
        """Write trigger YAML per leaf from the scope template + trigger shell (see default.config.yaml).

        **Missing** triggers are always created. **Existing** trigger files are **skipped** unless
        ``overwrite=True`` (``--force``), so embedded ``configuration`` is not overwritten after
        initial creation unless the operator opts in.
        Returns paths that were written (or would be in dry-run); returns ``None`` when there are
        no leaf contexts.
        """
        root = module_root if module_root is not None else (
            contexts[0].module_root if contexts else None
        )
        if not contexts:
            logger.info("No leaf scopes; skip workflow triggers")
            if not dry_run and root is not None:
                _cleanup_legacy_trigger_layout(root / WORKFLOW_ARTIFACTS_REL)
            return None
        module_root = contexts[0].module_root
        workflows_dir = module_root / WORKFLOW_ARTIFACTS_REL
        template_text = _read_trigger_template(module_root, self._template_path_override)
        scope_tpl = _read_scope_document_template(module_root, self._scope_document_path_override)
        triggers = _render_triggers(
            template_text,
            scope_tpl,
            contexts,
            workflow_base=self._workflow_base,
        )
        created: list[Path] = []
        skipped_existing = 0
        header = (
            "# Generated by scripts/build_scopes.py (workflow_triggers builder). "
            "# Created if missing; pass --force to overwrite trigger from templates + trimmed configuration. "
            "Full unified scope is always written to sibling *.config.yaml (see --check-workflow-triggers). "
            "use --check-workflow-triggers in CI to catch drift.\n"
            "# Trigger shell: workflow_template/workflow.template.WorkflowTrigger.yaml\n"
            "# Scope body: workflow_template/workflow.template.config.yaml (unified graph + config)\n"
            "# Cron uses {{ workflow_schedule }} from default.config.yaml. Toolkit substitutes "
            "{{function_client_id}}, {{function_client_secret}}, and {{instance_space}} inside "
            "configuration at deploy time.\n"
        )
        for ctx, (trig, full_scope) in zip(contexts, triggers, strict=True):
            suffix = cdf_external_id_suffix(ctx.scope_id)
            out_path = trigger_output_path(
                workflows_dir=workflows_dir,
                workflow_base=self._workflow_base,
                suffix=suffix,
            )
            cfg_path = scope_config_document_path(
                workflows_dir=workflows_dir,
                workflow_base=self._workflow_base,
                suffix=suffix,
            )
            if dry_run:
                logger.info("[dry-run] would write full scope %s", cfg_path.name)
                if out_path.is_file() and not self._overwrite:
                    skipped_existing += 1
                    logger.info("[dry-run] would skip existing %s (pass --force to overwrite)", out_path)
                    continue
                created.append(out_path)
                if out_path.is_file():
                    logger.info("[dry-run] would refresh %s", out_path)
                else:
                    logger.info("[dry-run] would write %s", out_path)
                continue
            out_path.parent.mkdir(parents=True, exist_ok=True)
            _write_scope_full_config_yaml(cfg_path, full_scope)
            logger.info("Wrote full scope %s", cfg_path)
            if out_path.is_file() and not self._overwrite:
                skipped_existing += 1
                logger.info("Skipping existing workflow trigger %s (pass --force to overwrite)", out_path.name)
                continue
            if out_path.is_file():
                logger.info("Refreshing workflow trigger %s", out_path.name)
            with open(out_path, "w", encoding="utf-8") as f:
                f.write(header)
                yaml.safe_dump(
                    trig,
                    f,
                    default_flow_style=False,
                    allow_unicode=True,
                    sort_keys=False,
                )
            logger.info("Wrote %s", out_path)
            created.append(out_path)

        if not dry_run:
            _cleanup_legacy_trigger_layout(workflows_dir)

        logger.info(
            "Workflow triggers: wrote %d, skipped %d existing",
            len(created),
            skipped_existing,
        )
        return created


def _read_trigger_template(module_root: Path, override: Path | None) -> str:
    path = override if override is not None else (module_root / DEFAULT_TRIGGER_TEMPLATE_REL)
    if not path.is_file():
        raise FileNotFoundError(f"Workflow trigger template not found: {path}")
    return path.read_text(encoding="utf-8")


def _read_scope_document_template(module_root: Path, override: Path | None) -> dict:
    path = override if override is not None else (module_root / DEFAULT_SCOPE_DOCUMENT_REL)
    return load_scope_document_dict_for_build(path)


def _render_triggers(
    template_text: str,
    scope_template: dict,
    contexts: Sequence[ScopeBuildContext],
    *,
    workflow_base: str,
) -> List[Tuple[dict, dict]]:
    if PLACEHOLDER not in template_text:
        raise ValueError(
            f"Workflow trigger template must contain placeholder {PLACEHOLDER!r} "
            "(replaced with cdf_external_id_suffix per leaf)."
        )
    out: List[Tuple[dict, dict]] = []
    for ctx in contexts:
        suffix = cdf_external_id_suffix(ctx.scope_id)
        chunk = template_text.replace(PLACEHOLDER, suffix)
        wf_ext = scoped_workflow_external_id(workflow_base, suffix)
        chunk = chunk.replace("{{ workflow }}", wf_ext)
        trig = yaml.safe_load(chunk)
        if not isinstance(trig, dict):
            raise ValueError("Workflow trigger template must be a single YAML mapping (one trigger)")
        inp = trig.setdefault("input", {})
        scope_document = prepare_scope_document_for_context(scope_template, ctx)
        configuration = scope_configuration_for_workflow_trigger(scope_document)
        assert_scope_document_within_limit(configuration, scope_id=ctx.scope_id)
        inp["configuration"] = configuration
        assert_workflow_trigger_input_within_limit(inp, scope_id=ctx.scope_id)
        out.append((trig, scope_document))
    return out


def _scope_document_normalized_for_compare(doc: dict) -> dict:
    """Match :func:`scope_build.scope_yaml_io.load_scope_document_dict_normalized` graph hoist."""
    from functions.cdf_fn_common.scope_canvas_merge import normalize_root_graph_into_canvas

    d = deepcopy(doc)
    normalize_root_graph_into_canvas(d)
    return d


def verify_triggers_file(
    module_root: Path,
    contexts: List[ScopeBuildContext],
    *,
    template_path: Path | None = None,
    scope_document_path: Path | None = None,
    workflow_base: str = "key_extraction_aliasing",
) -> None:
    """Raise SystemExit(1) if a required trigger or leaf scope config is missing, invalid YAML, or out of date."""
    from scope_build.scope_yaml_io import load_scope_document_dict_normalized

    workflows_dir = module_root / WORKFLOW_ARTIFACTS_REL
    legacy = workflows_dir / LEGACY_MONOLITHIC_NAME
    if legacy.is_file():
        raise SystemExit(
            f"Legacy {LEGACY_MONOLITHIC_NAME} is present; run:\n"
            f"  python {module_root / 'scripts' / 'build_scopes.py'}\n"
            "to generate per-scope WorkflowTrigger.yaml files."
        )
    template_text = _read_trigger_template(module_root, template_path)
    scope_tpl = _read_scope_document_template(module_root, scope_document_path)
    expected_trigger_by_relpath: dict[str, dict] = {}
    expected_scope_cfg_by_relpath: dict[str, dict] = {}
    for ctx in contexts:
        suffix = cdf_external_id_suffix(ctx.scope_id)
        name = workflow_trigger_filename(workflow_base, suffix)
        rel = str(WORKFLOW_ARTIFACTS_REL / suffix / name)
        cfg_name = scope_config_filename(workflow_base, suffix)
        cfg_rel = str(WORKFLOW_ARTIFACTS_REL / suffix / cfg_name)
        exp_trig, exp_full = _render_triggers(
            template_text,
            scope_tpl,
            [ctx],
            workflow_base=workflow_base,
        )[0]
        expected_trigger_by_relpath[rel] = exp_trig
        expected_scope_cfg_by_relpath[cfg_rel] = exp_full

    for rel, exp in expected_trigger_by_relpath.items():
        path = module_root / rel
        if not path.is_file():
            raise SystemExit(
                f"Missing workflow trigger file for current hierarchy: {rel}. "
                f"Run:\n  python {module_root / 'scripts' / 'build_scopes.py'}"
            )
        body = strip_leading_comments_and_blanks(path.read_text(encoding="utf-8"))
        try:
            existing = yaml.safe_load(body)
        except yaml.YAMLError as e:
            raise SystemExit(f"Invalid YAML in {path}: {e}") from e
        if existing != exp:
            raise SystemExit(
                f"{rel} is out of date. Run:\n"
                f"  python {module_root / 'scripts' / 'build_scopes.py'} --force"
            )

    for cfg_rel, exp_full in expected_scope_cfg_by_relpath.items():
        cfg_path = module_root / cfg_rel
        if not cfg_path.is_file():
            raise SystemExit(
                f"Missing leaf scope config (full source of truth): {cfg_rel}. "
                f"Run:\n  python {module_root / 'scripts' / 'build_scopes.py'}"
            )
        try:
            disk_full = load_scope_document_dict_normalized(cfg_path)
        except ValueError as e:
            raise SystemExit(f"Invalid scope YAML in {cfg_rel}: {e}") from e
        exp_norm = _scope_document_normalized_for_compare(exp_full)
        if disk_full != exp_norm:
            raise SystemExit(
                f"{cfg_rel} is out of date. Run:\n"
                f"  python {module_root / 'scripts' / 'build_scopes.py'} --force"
            )
