space: rmdm
externalId: rmdm_v1
name: Reliability Maintenance Data Model 
description: 'Reliability & Maintenance Data Model, ISO14224 compliant'
version: v1
views:
- space: cdf_cdm
  externalId: Cognite360Image
  version: v1
  type: view
- space: cdf_cdm
  externalId: Cognite360ImageAnnotation
  version: v1
  type: view
- space: cdf_cdm
  externalId: Cognite360ImageCollection
  version: v1
  type: view
- space: cdf_cdm
  externalId: Cognite360ImageModel
  version: v1
  type: view
- space: cdf_cdm
  externalId: Cognite360ImageStation
  version: v1
  type: view
- space: cdf_cdm
  externalId: Cognite3DModel
  version: v1
  type: view
- space: cdf_cdm
  externalId: Cognite3DObject
  version: v1
  type: view
- space: cdf_cdm
  externalId: Cognite3DRevision
  version: v1
  type: view
- space: cdf_cdm
  externalId: Cognite3DTransformation
  version: v1
  type: view
- space: cdf_cdm
  externalId: CogniteActivity
  version: v1
  type: view
- space: cdf_cdm
  externalId: CogniteAnnotation
  version: v1
  type: view
- space: cdf_cdm
  externalId: CogniteAsset
  version: v1
  type: view
- space: cdf_cdm
  externalId: CogniteAssetClass
  version: v1
  type: view
- space: cdf_cdm
  externalId: CogniteAssetType
  version: v1
  type: view
- space: cdf_cdm
  externalId: CogniteCADModel
  version: v1
  type: view
- space: cdf_cdm
  externalId: CogniteCADNode
  version: v1
  type: view
- space: cdf_cdm
  externalId: CogniteCADRevision
  version: v1
  type: view
- space: cdf_cdm
  externalId: CogniteCubeMap
  version: v1
  type: view
- space: cdf_cdm
  externalId: CogniteDescribable
  version: v1
  type: view
- space: cdf_cdm
  externalId: CogniteDiagramAnnotation
  version: v1
  type: view
- space: cdf_cdm
  externalId: CogniteEquipment
  version: v1
  type: view
- space: cdf_cdm
  externalId: CogniteEquipmentType
  version: v1
  type: view
- space: cdf_cdm
  externalId: CogniteFile
  version: v1
  type: view
- space: cdf_cdm
  externalId: CogniteFileCategory
  version: v1
  type: view
- space: cdf_cdm
  externalId: CognitePointCloudModel
  version: v1
  type: view
- space: cdf_cdm
  externalId: CognitePointCloudRevision
  version: v1
  type: view
- space: cdf_cdm
  externalId: CognitePointCloudVolume
  version: v1
  type: view
- space: cdf_cdm
  externalId: CogniteSchedulable
  version: v1
  type: view
- space: cdf_cdm
  externalId: CogniteSourceSystem
  version: v1
  type: view
- space: cdf_cdm
  externalId: CogniteSourceable
  version: v1
  type: view
- space: cdf_cdm
  externalId: CogniteTimeSeries
  version: v1
  type: view
- space: cdf_cdm
  externalId: CogniteUnit
  version: v1
  type: view
- space: cdf_cdm
  externalId: CogniteVisualizable
  version: v1
  type: view
- space: cdf_idm
  externalId: CogniteMaintenanceOrder
  version: v1
  type: view
- space: cdf_idm
  externalId: CogniteNotification
  version: v1
  type: view
- space: cdf_idm
  externalId: CogniteOperation
  version: v1
  type: view
- space: rmdm
  externalId: Asset
  version: v1
  type: view
- space: rmdm
  externalId: Equipment
  version: v1
  type: view
- space: rmdm
  externalId: EquipmentClass
  version: v1
  type: view
- space: rmdm
  externalId: EquipmentFunction
  version: v1
  type: view
- space: rmdm
  externalId: EquipmentType
  version: v1
  type: view
- space: rmdm
  externalId: FailureCause
  version: v1
  type: view
- space: rmdm
  externalId: FailureMechanism
  version: v1
  type: view
- space: rmdm
  externalId: FailureMode
  version: v1
  type: view
- space: rmdm
  externalId: FailureNotification
  version: v1
  type: view
- space: rmdm
  externalId: File_ext
  version: v1
  type: view
- space: rmdm
  externalId: MaintenanceOrder
  version: v1
  type: view
- space: rmdm
  externalId: Notification
  version: v1
  type: view
- space: rmdm
  externalId: Timeseries_ext
  version: v1
  type: view
