#!/usr/bin/env python3
"""Generate config.{dev,test,prod}.yaml for FDP CI from module default.config.yaml files."""

from __future__ import annotations

import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    print("PyYAML is required: pip install pyyaml", file=sys.stderr)
    sys.exit(1)

# Module paths under the organization directory (modules/ is the Toolkit modules root).
FDP_MODULE_PATHS: list[str] = [
    "data_models/isa_manufacturing_extension",
    "sourcesystem/cdf_pi_foundation",
    "sourcesystem/cdf_opcua_foundation",
    "sourcesystem/cdf_sap_foundation",
    "sourcesystem/cdf_db_foundation",
    "sourcesystem/cdf_files_foundation",
]

def selected_module_entries() -> list[str]:
    return [f"modules/{path}" for path in FDP_MODULE_PATHS]

ENVIRONMENTS = ("dev", "test", "prod")

FDP_ROOT = Path(__file__).resolve().parents[1]
REPO_ROOT = FDP_ROOT.parent
MODULES_ROOT = REPO_ROOT / "modules"


def module_variable_key(module_path: str) -> str:
    return Path(module_path).name


def load_default_config(module_path: str) -> dict:
    config_path = MODULES_ROOT / module_path / "default.config.yaml"
    if not config_path.is_file():
        return {}
    with config_path.open(encoding="utf-8") as handle:
        data = yaml.safe_load(handle) or {}
    if not isinstance(data, dict):
        raise ValueError(f"Expected mapping in {config_path}")
    return data


def build_config(env_name: str) -> dict:
    variables_modules: dict[str, dict] = {}
    flat_variables: dict = {}
    for module_path in FDP_MODULE_PATHS:
        defaults = load_default_config(module_path)
        if defaults:
            variables_modules[module_variable_key(module_path)] = defaults
            flat_variables.update(defaults)

    return {
        "environment": {
            "name": env_name,
            "project": f"at-{env_name}",
            "validation-type": "dev",
            "selected": selected_module_entries(),
        },
        "variables": {**flat_variables, "modules": variables_modules},
    }


def main() -> None:
    for env_name in ENVIRONMENTS:
        out_path = FDP_ROOT / f"config.{env_name}.yaml"
        payload = build_config(env_name)
        header = (
            "# Generated by foundation-deployment-pack/scripts/generate_env_configs.py\n"
            "# Re-run .github/scripts/prepare-fdp-project.sh to refresh.\n"
        )
        with out_path.open("w", encoding="utf-8") as handle:
            handle.write(header)
            yaml.safe_dump(
                payload,
                handle,
                default_flow_style=False,
                sort_keys=False,
                allow_unicode=True,
            )
        print(f"Wrote {out_path.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
