name: producer_{{location}}_ep_db_{{sourceSystem}}_{{environment}}
sourceId: {{extractor_group_source_id}}
capabilities:
  - datasetsAcl:
      actions: [READ]
      scope:
        idScope:
          ids: ["{{dataset}}"]
  - rawAcl:
      actions: [READ, WRITE, LIST]
      scope:
        tableScope:
          dbsToTables:
            raw_asset_{{location}}_{{sourceSystem}}: []
  - extractionPipelinesAcl:
      actions: [READ]
      scope:
        datasetScope:
          ids: ["{{dataset}}"]
  - extractionConfigsAcl:
      actions: [READ]
      scope:
        datasetScope:
          ids: ["{{dataset}}"]
  - extractionRunsAcl:
      actions: [WRITE]
      scope:
        datasetScope:
          ids: ["{{dataset}}"]
