location: springfield
location_name: Springfield
location_description: Springfield site demo
module_version: "v1"

# Source IDs from your identity provider for the Infield user groups.
infield_location_read_only_users_source_id: <change_me>
infield_location_normal_users_source_id: <change_me>
infield_location_template_admin_users_source_id: <change_me>
infield_location_checklist_admin_users_source_id: <change_me>
