environment:
  name: dev
  project: shivam-qs
  validation-type: dev
  selected:
  - modules/

variables:
  modules:
    accelerators:
      contextualization:
        cdf_three_dimenssion:
          default_location: ${default_location}
          source_name: ${source_name}
          raw_db: ${RAW_DB}          # raw database name for manual mappings
          raw_table_manual: contextualization_manual_input
          raw_table_asset_staging: asset_hierarchy_staging
          function_space: ${FUNCTION_SPACE}
          3d_model_name: ${3d_model_name}   # 3d_model_name is the "name" property of cognite3dmodel
          cad_model_name: cdf_cdm
          cad_model_type: CAD
          default_cad_space: cdf_cdm
          default_dm_space: cdf_cdm
          data_model_space: cdf_cdm
          dm_ext_id: ${DM_EXT_ID}  # data model external id for the project
          dm_version: ${DM_VERSION}
          default_scene_space: scene
          cad_contextualization_batch_size: 100
          required_views:
          - space: cdf_cdm
            external_id: Cognite3DObject
            version: v1

          - space: cdf_cdm
            external_id: CogniteCADNode
            version: v1

          - space: cdf_cdm
            external_id: CogniteCADRevision
            version: v1

          - space: cdf_cdm
            external_id: CogniteCADModel
            version: v1

          - space: cdf_cdm
            external_id: Cognite3DRevision
            version: v1

          - space: cdf_cdm
            external_id: Cognite3DModel
            version: v1

          - space: cdf_cdm
            external_id: Cognite3DTransformation
            version: v1

          - space: cdf_cdm
            external_id: CogniteVisualizable
            version: v1

          - space: cdf_cdm
            external_id: Cognite360Image
            version: v1

          - space: cdf_cdm
            external_id: Cognite360ImageAnnotation
            version: v1

          - space: cdf_cdm
            external_id: CogniteAnnotation
            version: v1

          - space: cdf_cdm
            external_id: Cognite360ImageCollection
            version: v1

          - space: cdf_cdm
            external_id: Cognite360ImageStation
            version: v1

          - space: cdf_cdm
            external_id: CognitePointCloudVolume
            version: v1

          - space: cdf_cdm
            external_id: CognitePointCloudRevision
            version: v1

          - space: scene
            external_id: SceneConfiguration
            version: v1

          - space: scene
            external_id: RevisionProperties
            version: v1

          - space: cdf_3d_schema
            external_id: Cdf3dModel
            version: '1'

          asset_instance_space: ${ASSET_INSTANCE_SPACE}
          cad_node_instance_space: ${CAD_NODE_INSTANCE_SPACE}
          asset_view_ext_id: ${ASSET_VIEW_EXT_ID}          #view where asset are available for contextualization
          asset_view_version: ${ASSET_VIEW_VERSION}          #version of the view where asset are available for contextualization
          file_extractor_watch_path: c:/tmp/files
          3d_location_group_source_id: ${3d_location_group_source_id}   #group source id for the project
          cicd_clientId: ${cicd_clientId}
          cicd_clientSecret: ${cicd_clientSecret}
          cicd_tokenUri: ${IDP_TOKEN_URL}
          cdf_project_name: ${CDF_PROJECT}
          cdf_cluster: ${CDF_CLUSTER}
          external_root_id_asset: ${EXTERNAL_ROOT_ID_ASSET}  #optional: only used for legacy behavior
          cad_model_view:
            space: cdf_cdm
            external_id: CogniteCADModel
            version: v1

          cad_revision_view:
            space: cdf_cdm
            external_id: CogniteCADRevision
            version: v1

          scene_config_view:
            space: scene
            external_id: SceneConfiguration
            version: v1

          scene_model_view:
            space: cdf_3d_schema
            external_id: Cdf3dModel
            version: '1'

          rev_props_view:
            space: scene
            external_id: RevisionProperties
            version: v1
