schemaSpace: dm_dom_oil_and_gas
organization: ORG
datamodelExternalId: dm_oil_and_gas_domain_model
datamodelVersion: v1
dataset: ingestion
instanceSpace: inst_location
activityToTimeSeriesTransformationExternalId: activity_to_timeseries
maintenanceOrderToAssetTransformationExternalId: maintenance_order_to_asset
operationToAssetTransformationExternalId: operation_to_asset
timeSeriesToEquipmentTransformationExternalId: timeseries_to_equipment
