name: producer_{{location}}_ep_opcua_{{sourceSystem}}_{{environment}}
sourceId: {{extractor_group_source_id}}
capabilities:
  - datasetsAcl:
      actions: [READ]
      scope:
        idScope:
          ids: ["{{dataset}}"]
  - rawAcl:
      actions: [READ, WRITE, LIST]
      scope:
        tableScope:
          dbsToTables:
            raw_asset_{{location}}_{{sourceSystem}}: []
  - timeSeriesAcl:
      actions: [READ, WRITE]
      scope:
        datasetScope:
          ids: ["{{dataset}}"]
  - dataModelInstancesAcl:
      actions: [READ, WRITE, WRITE_PROPERTIES]
      scope:
        spaceIdScope:
          spaceIds: ["{{instanceSpace}}"]
  - extractionPipelinesAcl:
      actions: [READ]
      scope:
        datasetScope:
          ids: ["{{dataset}}"]
  - extractionConfigsAcl:
      actions: [READ]
      scope:
        datasetScope:
          ids: ["{{dataset}}"]
  - extractionRunsAcl:
      actions: [WRITE]
      scope:
        datasetScope:
          ids: ["{{dataset}}"]
