"""Copy ``workflow.input.configuration`` from one leaf trigger to another (destination-patched)."""

from __future__ import annotations

import argparse
import logging
import sys
from pathlib import Path
from typing import Any, Dict, Sequence

import yaml

from scope_build.hierarchy import build_contexts, load_hierarchy_doc
from scope_build.io_util import strip_leading_comments_and_blanks
from scope_build.mode import scope_build_mode_from_doc
from scope_build.orchestrate import (
    DEFAULT_HIERARCHY,
    module_root_from_package,
    workflow_external_id_from_hierarchy,
)
from scope_build.scope_document_patch import reconcile_scope_document_for_destination
from scope_build.workflow_trigger_paths import resolve_workflow_trigger_path_and_context

logger = logging.getLogger(__name__)

WORKFLOW_TRIGGER_YAML_HEADER = (
    "# Generated by scripts/build_scopes.py (workflow_triggers builder). "
    "# --build creates this file only if it is missing (--force overwrites from templates); "
    "delete it to recreate, or use --check-workflow-triggers in CI to catch drift.\n"
    "# Trigger shell: workflow_template/workflow.template.WorkflowTrigger.yaml\n"
    "# Scope body: workflow_template/workflow.template.config.yaml\n"
    "# Toolkit substitutes {{ key_extraction_aliasing_schedule }}, {{functionClientId}}, "
    "{{functionClientSecret}}, and {{instance_space}} inside configuration at deploy time.\n"
    "# input block updated by: python module.py copy-workflow-config ...\n"
)


def _load_trigger_mapping(path: Path) -> Dict[str, Any]:
    if not path.is_file():
        raise FileNotFoundError(
            f"Workflow trigger not found: {path}. Run ``python module.py build`` to generate it."
        )
    raw = path.read_text(encoding="utf-8")
    body = strip_leading_comments_and_blanks(raw)
    doc = yaml.safe_load(body)
    if not isinstance(doc, dict):
        raise ValueError(f"Workflow trigger root must be a mapping: {path}")
    return doc


def _normalize_run_id(val: Any) -> str:
    if val is None:
        return ""
    return str(val)


def _build_new_input(
    *,
    source_input: Dict[str, Any],
    dest_input_existing: Dict[str, Any],
    reconciled_configuration: Dict[str, Any],
    copy_run_fields: bool,
) -> Dict[str, Any]:
    if copy_run_fields:
        full_rescan = bool(source_input.get("full_rescan", False))
        run_id = _normalize_run_id(source_input.get("run_id"))
    else:
        full_rescan = bool(dest_input_existing.get("full_rescan", False))
        run_id = _normalize_run_id(dest_input_existing.get("run_id"))
    return {
        "full_rescan": full_rescan,
        "run_id": run_id,
        "configuration": reconciled_configuration,
    }


def run_copy_workflow_config(argv: Sequence[str] | None) -> int:
    p = argparse.ArgumentParser(
        description=(
            "Copy workflow.input.configuration from one leaf WorkflowTrigger.yaml to another. "
            "Only the top-level ``input`` key is replaced; destination-specific fields inside "
            "``configuration`` are reconciled like ``module.py build`` (external IDs, scope block, "
            "workflow_scope, instance-space filters)."
        )
    )
    p.add_argument(
        "--from",
        dest="from_spec",
        required=True,
        metavar="SCOPE_OR_PATH",
        help="Source: path to *.WorkflowTrigger.yaml or leaf scope_id",
    )
    p.add_argument(
        "--to",
        dest="to_spec",
        required=True,
        metavar="SCOPE_OR_PATH",
        help="Destination: path or scope_id",
    )
    p.add_argument(
        "--hierarchy",
        "-f",
        type=Path,
        default=None,
        help=f"Hierarchy YAML (default: module / {DEFAULT_HIERARCHY})",
    )
    p.add_argument(
        "--copy-run-fields",
        action="store_true",
        help="Also copy full_rescan and run_id from the source trigger (default: keep destination values).",
    )
    p.add_argument(
        "--dry-run",
        action="store_true",
        help="Log actions only; do not write the destination file",
    )
    p.add_argument(
        "--verbose",
        "-v",
        action="store_true",
        help="Debug logging",
    )
    args = p.parse_args(list(argv) if argv is not None else None)

    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(levelname)s %(message)s",
    )

    module_root = module_root_from_package()
    hierarchy_path = args.hierarchy or (module_root / DEFAULT_HIERARCHY)
    doc = load_hierarchy_doc(hierarchy_path)
    mode = scope_build_mode_from_doc(doc)
    workflow_base = workflow_external_id_from_hierarchy(doc)
    contexts = build_contexts(module_root=module_root, doc=doc, dry_run=True)

    src_path, _src_ctx = resolve_workflow_trigger_path_and_context(
        args.from_spec,
        module_root=module_root,
        contexts=contexts,
        workflow_base=workflow_base,
        mode=mode,
    )
    dst_path, dst_ctx = resolve_workflow_trigger_path_and_context(
        args.to_spec,
        module_root=module_root,
        contexts=contexts,
        workflow_base=workflow_base,
        mode=mode,
    )

    if src_path.resolve() == dst_path.resolve():
        logger.error("Source and destination are the same file: %s", src_path)
        return 1

    src_doc = _load_trigger_mapping(src_path)
    src_inp = src_doc.get("input")
    if not isinstance(src_inp, dict):
        logger.error("Source trigger has no mapping at input: %s", src_path)
        return 1
    src_cfg = src_inp.get("configuration")
    if not isinstance(src_cfg, dict):
        logger.error("Source trigger input.configuration must be a mapping: %s", src_path)
        return 1

    dst_doc = _load_trigger_mapping(dst_path)
    dst_inp_existing = dst_doc.get("input")
    if not isinstance(dst_inp_existing, dict):
        dst_inp_existing = {}

    reconciled = reconcile_scope_document_for_destination(src_cfg, dst_ctx)
    new_input = _build_new_input(
        source_input=src_inp,
        dest_input_existing=dst_inp_existing,
        reconciled_configuration=reconciled,
        copy_run_fields=bool(args.copy_run_fields),
    )

    out_doc = dict(dst_doc)
    out_doc["input"] = new_input

    if args.dry_run:
        logger.info("[dry-run] would write input to %s (from %s)", dst_path, src_path)
        return 0

    dst_path.parent.mkdir(parents=True, exist_ok=True)
    with open(dst_path, "w", encoding="utf-8") as f:
        f.write(WORKFLOW_TRIGGER_YAML_HEADER)
        yaml.safe_dump(
            out_doc,
            f,
            default_flow_style=False,
            allow_unicode=True,
            sort_keys=False,
        )
    logger.info("Wrote %s", dst_path)
    return 0


def main(argv: Sequence[str] | None = None) -> int:
    try:
        return run_copy_workflow_config(argv)
    except (OSError, ValueError, FileNotFoundError) as e:
        logger = logging.getLogger(__name__)
        logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
        logger.error("%s", e)
        return 1


if __name__ == "__main__":
    sys.exit(main())
