"""Materialize v1 scope document ``key_extraction_aliasing.yaml`` per scope directory."""

from __future__ import annotations

import copy
import logging
import re
from pathlib import Path
from typing import Any, Dict, List

import yaml

from scope_build.context import ScopeBuildContext

logger = logging.getLogger(__name__)

_EXTERNAL_ID_SAFE = re.compile(r"[^a-zA-Z0-9_-]+")


def _cdf_external_id_suffix(scope_id: str) -> str:
    s = scope_id.lower().replace("__", "_")
    s = _EXTERNAL_ID_SAFE.sub("_", s)
    s = re.sub(r"_+", "_", s).strip("_")
    return s or "scope"


SCOPE_DOCUMENT_FILENAME = "key_extraction_aliasing.yaml"


class ScopeYamlBuilder:
    name = "key_extraction_aliasing"

    def __init__(self, template_path: Path) -> None:
        self._template_path = template_path

    def run(self, ctx: ScopeBuildContext) -> None:
        scopes_dir = ctx.module_root / "config" / "scopes"
        out_dir = scopes_dir / ctx.scope_id
        out_file = out_dir / SCOPE_DOCUMENT_FILENAME
        if out_file.is_file():
            logger.info("Skip existing %s", out_file)
            return
        if not self._template_path.is_file():
            raise FileNotFoundError(f"Template not found: {self._template_path}")
        if ctx.dry_run:
            logger.info("[dry-run] would create %s from %s", out_file, self._template_path)
            return

        out_dir.mkdir(parents=True, exist_ok=True)
        with open(self._template_path, "r", encoding="utf-8") as f:
            doc = yaml.safe_load(f)
        if not isinstance(doc, dict):
            raise ValueError("Template root must be a mapping")
        doc = copy.deepcopy(doc)
        suffix = _cdf_external_id_suffix(ctx.scope_id)
        _patch_external_ids(doc, suffix)
        _inject_leaf_instance_space_filters(doc, ctx)
        doc["scope"] = _build_scope_block(ctx)
        with open(out_file, "w", encoding="utf-8") as f:
            f.write(
                "# Generated by build_scopes.py (key_extraction_aliasing builder); "
                "safe to edit — re-runs skip this file if it exists.\n"
            )
            yaml.safe_dump(
                doc,
                f,
                default_flow_style=False,
                allow_unicode=True,
                sort_keys=False,
            )
        logger.info("Wrote %s", out_file)


def _build_scope_block(ctx: ScopeBuildContext) -> Dict[str, Any]:
    leaf = ctx.path[-1]
    return {
        "id": ctx.scope_id,
        "name": leaf.name,
        "description": leaf.description,
        "path": [
            {
                "level": step.level,
                "id": step.segment_id,
                "name": step.name,
                "description": step.description,
            }
            for step in ctx.path
        ],
    }


def _filter_is_node_space(f: Any) -> bool:
    if not isinstance(f, dict):
        return False
    scope = str(f.get("property_scope", "view")).lower()
    return scope == "node" and f.get("target_property") == "space"


def _inject_leaf_instance_space_filters(doc: Dict[str, Any], ctx: ScopeBuildContext) -> None:
    """Prepend a node `space` filter on each template source_view (unless one already exists).

    Uses the leaf hierarchy node's ``instance_space`` when set; otherwise a placeholder
    string embedding the scope id so authors can find and replace it.
    """
    ke = doc.get("key_extraction")
    if not isinstance(ke, dict):
        return
    cfg = ke.get("config")
    if not isinstance(cfg, dict):
        return
    data = cfg.get("data")
    if not isinstance(data, dict):
        return
    views = data.get("source_views")
    if not isinstance(views, list) or not views:
        return

    leaf_node: Dict[str, Any] = ctx.path[-1].node if ctx.path else {}
    inst = leaf_node.get("instance_space") if isinstance(leaf_node, dict) else None
    if isinstance(inst, str) and inst.strip():
        space_value = inst.strip()
    else:
        suffix = _cdf_external_id_suffix(ctx.scope_id)
        space_value = f"PLACEHOLDER_INSTANCE_SPACE_FOR_SCOPE__{suffix}"

    for v in views:
        if not isinstance(v, dict):
            continue
        raw_filters = v.get("filters")
        if raw_filters is None:
            flist: List[Any] = []
        elif isinstance(raw_filters, list):
            flist = list(raw_filters)
        else:
            flist = []
        if any(_filter_is_node_space(f) for f in flist):
            continue
        node_filter: Dict[str, Any] = {
            "operator": "EQUALS",
            "property_scope": "node",
            "target_property": "space",
            "values": [space_value],
        }
        v["filters"] = [node_filter] + flist


def _patch_external_ids(doc: Dict[str, Any], suffix: str) -> None:
    ke = doc.get("key_extraction")
    if isinstance(ke, dict) and "externalId" in ke:
        base = str(ke["externalId"])
        ke["externalId"] = _with_suffix(base, suffix)
    al = doc.get("aliasing")
    if isinstance(al, dict) and "externalId" in al:
        base = str(al["externalId"])
        al["externalId"] = _with_suffix(base, suffix)


def _with_suffix(base: str, suffix: str) -> str:
    if base.endswith("_default"):
        stem = base[: -len("_default")]
        return f"{stem}_{suffix}"
    return f"{base}_{suffix}"
