"""Emit Workflow / WorkflowVersion YAML from templates (create if missing)."""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Sequence

import yaml

from scope_build.context import ScopeBuildContext
from scope_build.hierarchy import workflow_display_name_from_path
from scope_build.paths import WORKFLOW_ARTIFACTS_REL, WORKFLOW_TEMPLATE_REL
from scope_build.io_util import strip_leading_comments_and_blanks
from scope_build.mode import scoped_workflow_external_id
from scope_build.naming import cdf_external_id_suffix

logger = logging.getLogger(__name__)

WORKFLOW_EXTERNAL_ID_PLACEHOLDER = "__KEA_WORKFLOW_EXTERNAL_ID__"

DEFAULT_WORKFLOW_TEMPLATE_REL = (
    WORKFLOW_TEMPLATE_REL / "workflow.template.Workflow.yaml"
)
DEFAULT_WORKFLOW_VERSION_TEMPLATE_REL = (
    WORKFLOW_TEMPLATE_REL / "workflow.template.WorkflowVersion.yaml"
)


def _read_text_template(module_root: Path, rel: Path, override: Path | None) -> str:
    path = override if override is not None else (module_root / rel)
    if not path.is_file():
        raise FileNotFoundError(f"Workflow template not found: {path}")
    return path.read_text(encoding="utf-8")


def render_workflow_template_text(
    template_text: str,
    workflow_external_id: str,
    *,
    display_name: str | None = None,
) -> str:
    if WORKFLOW_EXTERNAL_ID_PLACEHOLDER not in template_text:
        raise ValueError(
            f"Workflow template must contain placeholder {WORKFLOW_EXTERNAL_ID_PLACEHOLDER!r}"
        )
    body = template_text.replace(WORKFLOW_EXTERNAL_ID_PLACEHOLDER, workflow_external_id)
    dn = (display_name or "").strip()
    if dn:
        name_line = yaml.dump({"name": dn}, default_flow_style=False, allow_unicode=True).rstrip()
        lines = body.splitlines()
        out: list[str] = []
        inserted = False
        for line in lines:
            out.append(line)
            if not inserted and line.startswith("externalId:"):
                out.append(name_line)
                inserted = True
        if not inserted:
            raise ValueError("Workflow template must contain an externalId mapping for name injection")
        body = "\n".join(out)
        if template_text.endswith("\n") and not body.endswith("\n"):
            body += "\n"
    yaml.safe_load(body)  # validate
    return body


class RootWorkflowDefinitionsBuilder:
    """trigger_only: write ``workflows/{workflow_base}.Workflow.yaml`` (+ Version) once if missing."""

    name = "workflow_definitions_root"

    def __init__(
        self,
        *,
        workflow_base: str,
        workflow_template_path: Path | None = None,
        workflow_version_template_path: Path | None = None,
        overwrite: bool = False,
    ) -> None:
        self._workflow_base = workflow_base
        self._workflow_template_override = workflow_template_path
        self._workflow_version_template_override = workflow_version_template_path
        self._overwrite = overwrite

    def run(self, ctx: ScopeBuildContext) -> None:
        """No-op; use ``write_once`` from orchestration (runs even when there are zero leaves)."""

    def write_once(self, module_root: Path, *, dry_run: bool) -> None:
        workflows_dir = module_root / WORKFLOW_ARTIFACTS_REL
        wf_tpl = _read_text_template(
            module_root,
            DEFAULT_WORKFLOW_TEMPLATE_REL,
            self._workflow_template_override,
        )
        wv_tpl = _read_text_template(
            module_root,
            DEFAULT_WORKFLOW_VERSION_TEMPLATE_REL,
            self._workflow_version_template_override,
        )
        wf_body = render_workflow_template_text(wf_tpl, self._workflow_base)
        wv_body = render_workflow_template_text(wv_tpl, self._workflow_base)
        wf_path = workflows_dir / f"{self._workflow_base}.Workflow.yaml"
        wv_path = workflows_dir / f"{self._workflow_base}.WorkflowVersion.yaml"
        header = (
            "# Generated by scripts/build_scopes.py (workflow_definitions_root). "
            "# --build creates these only if missing (--force overwrites from templates).\n"
            f"# Workflow template: workflow_template/workflow.template.Workflow.yaml\n"
            f"# WorkflowVersion template: workflow_template/workflow.template.WorkflowVersion.yaml\n"
        )
        for path, body in ((wf_path, wf_body), (wv_path, wv_body)):
            if dry_run:
                if path.is_file():
                    if self._overwrite:
                        logger.info("[dry-run] would overwrite %s", path)
                    else:
                        logger.info("[dry-run] would skip existing %s", path)
                else:
                    logger.info("[dry-run] would write %s", path)
                continue
            workflows_dir.mkdir(parents=True, exist_ok=True)
            if path.is_file() and not self._overwrite:
                logger.info("Skipping existing %s", path.name)
                continue
            if path.is_file() and self._overwrite:
                logger.info("Overwriting %s", path.name)
            with open(path, "w", encoding="utf-8") as f:
                f.write(header)
                f.write(body)
                if not body.endswith("\n"):
                    f.write("\n")
            logger.info("Wrote %s", path)


class ScopedWorkflowDefinitionsBuilder:
    """full: per leaf, write scoped Workflow + WorkflowVersion under workflows/<suffix>/."""

    name = "workflow_definitions_scoped"

    def __init__(
        self,
        *,
        workflow_base: str,
        workflow_template_path: Path | None = None,
        workflow_version_template_path: Path | None = None,
        overwrite: bool = False,
    ) -> None:
        self._workflow_base = workflow_base
        self._workflow_template_override = workflow_template_path
        self._workflow_version_template_override = workflow_version_template_path
        self._overwrite = overwrite

    def run(self, ctx: ScopeBuildContext) -> None:
        module_root = ctx.module_root
        suffix = cdf_external_id_suffix(ctx.scope_id)
        ext_id = scoped_workflow_external_id(self._workflow_base, suffix)
        wf_tpl = _read_text_template(
            module_root,
            DEFAULT_WORKFLOW_TEMPLATE_REL,
            self._workflow_template_override,
        )
        wv_tpl = _read_text_template(
            module_root,
            DEFAULT_WORKFLOW_VERSION_TEMPLATE_REL,
            self._workflow_version_template_override,
        )
        wf_body = render_workflow_template_text(
            wf_tpl,
            ext_id,
            display_name=workflow_display_name_from_path(ctx.path),
        )
        wv_body = render_workflow_template_text(wv_tpl, ext_id)
        scope_dir = module_root / WORKFLOW_ARTIFACTS_REL / suffix
        wf_name = f"{self._workflow_base}.{suffix}.Workflow.yaml"
        wv_name = f"{self._workflow_base}.{suffix}.WorkflowVersion.yaml"
        wf_path = scope_dir / wf_name
        wv_path = scope_dir / wv_name
        header = (
            "# Generated by scripts/build_scopes.py (workflow_definitions_scoped). "
            "# --build creates these only if missing (--force overwrites from templates).\n"
            f"# Workflow template: workflow_template/workflow.template.Workflow.yaml\n"
            f"# WorkflowVersion template: workflow_template/workflow.template.WorkflowVersion.yaml\n"
        )
        for path, body in ((wf_path, wf_body), (wv_path, wv_body)):
            if ctx.dry_run:
                if path.is_file():
                    if self._overwrite:
                        logger.info("[dry-run] would overwrite %s", path)
                    else:
                        logger.info("[dry-run] would skip existing %s", path)
                else:
                    logger.info("[dry-run] would write %s", path)
                continue
            scope_dir.mkdir(parents=True, exist_ok=True)
            if path.is_file() and not self._overwrite:
                logger.info("Skipping existing %s", path)
                continue
            if path.is_file() and self._overwrite:
                logger.info("Overwriting %s", path)
            with open(path, "w", encoding="utf-8") as f:
                f.write(header)
                f.write(body)
                if not body.endswith("\n"):
                    f.write("\n")
            logger.info("Wrote %s", path)


def expected_root_workflow_documents(
    module_root: Path,
    workflow_base: str,
    *,
    workflow_template_path: Path | None,
    workflow_version_template_path: Path | None,
) -> tuple[dict, dict]:
    wf_tpl = _read_text_template(
        module_root, DEFAULT_WORKFLOW_TEMPLATE_REL, workflow_template_path
    )
    wv_tpl = _read_text_template(
        module_root, DEFAULT_WORKFLOW_VERSION_TEMPLATE_REL, workflow_version_template_path
    )
    wf_doc = yaml.safe_load(render_workflow_template_text(wf_tpl, workflow_base))
    wv_doc = yaml.safe_load(render_workflow_template_text(wv_tpl, workflow_base))
    if not isinstance(wf_doc, dict) or not isinstance(wv_doc, dict):
        raise ValueError("Workflow templates must render to YAML mappings")
    return wf_doc, wv_doc


def expected_scoped_workflow_documents(
    module_root: Path,
    workflow_base: str,
    suffix: str,
    *,
    workflow_template_path: Path | None,
    workflow_version_template_path: Path | None,
    display_name: str | None = None,
) -> tuple[dict, dict]:
    ext_id = scoped_workflow_external_id(workflow_base, suffix)
    wf_tpl = _read_text_template(
        module_root, DEFAULT_WORKFLOW_TEMPLATE_REL, workflow_template_path
    )
    wv_tpl = _read_text_template(
        module_root, DEFAULT_WORKFLOW_VERSION_TEMPLATE_REL, workflow_version_template_path
    )
    wf_doc = yaml.safe_load(
        render_workflow_template_text(wf_tpl, ext_id, display_name=display_name)
    )
    wv_doc = yaml.safe_load(render_workflow_template_text(wv_tpl, ext_id))
    if not isinstance(wf_doc, dict) or not isinstance(wv_doc, dict):
        raise ValueError("Workflow templates must render to YAML mappings")
    return wf_doc, wv_doc


def _verify_kahn_graph_matches_workflow_version_template(
    module_root: Path,
    workflow_version_template_path: Path | None,
) -> None:
    """Ensure workflow.execution.graph.yaml agrees with WorkflowVersion template dependsOn."""
    from functions.cdf_fn_common.workflow_execution_graph import (
        validate_template_workflow_version_matches_execution_graph,
    )

    tpl = (
        workflow_version_template_path
        if workflow_version_template_path is not None
        else (module_root / DEFAULT_WORKFLOW_VERSION_TEMPLATE_REL)
    )
    errs = validate_template_workflow_version_matches_execution_graph(module_root, tpl)
    if errs:
        raise SystemExit(
            "workflow.execution.graph.yaml does not match WorkflowVersion template dependsOn:\n"
            + "\n".join(f"  - {e}" for e in errs)
        )


def verify_root_workflow_bundle(
    module_root: Path,
    workflow_base: str,
    *,
    workflow_template_path: Path | None,
    workflow_version_template_path: Path | None,
) -> None:
    """Raise SystemExit(1) if root Workflow / WorkflowVersion are missing or differ from templates."""
    _verify_kahn_graph_matches_workflow_version_template(
        module_root, workflow_version_template_path
    )
    workflows_dir = module_root / WORKFLOW_ARTIFACTS_REL
    exp_wf, exp_wv = expected_root_workflow_documents(
        module_root,
        workflow_base,
        workflow_template_path=workflow_template_path,
        workflow_version_template_path=workflow_version_template_path,
    )
    for path, exp in (
        (workflows_dir / f"{workflow_base}.Workflow.yaml", exp_wf),
        (workflows_dir / f"{workflow_base}.WorkflowVersion.yaml", exp_wv),
    ):
        if not path.is_file():
            raise SystemExit(
                f"Missing {path.relative_to(module_root)} for scope_build_mode=trigger_only. "
                f"Run:\n  python {module_root / 'scripts' / 'build_scopes.py'}"
            )
        body = strip_leading_comments_and_blanks(path.read_text(encoding="utf-8"))
        try:
            got = yaml.safe_load(body)
        except yaml.YAMLError as e:
            raise SystemExit(f"Invalid YAML in {path}: {e}") from e
        if got != exp:
            raise SystemExit(
                f"{path.name} is out of date vs templates. Run:\n"
                f"  python {module_root / 'scripts' / 'build_scopes.py'} --force"
            )


def verify_scoped_workflow_bundle(
    module_root: Path,
    workflow_base: str,
    ctx: ScopeBuildContext,
    *,
    workflow_template_path: Path | None,
    workflow_version_template_path: Path | None,
) -> None:
    """Raise SystemExit(1) if scoped Workflow / WorkflowVersion are missing or differ."""
    _verify_kahn_graph_matches_workflow_version_template(
        module_root, workflow_version_template_path
    )
    suffix = cdf_external_id_suffix(ctx.scope_id)
    scope_dir = module_root / WORKFLOW_ARTIFACTS_REL / suffix
    exp_wf, exp_wv = expected_scoped_workflow_documents(
        module_root,
        workflow_base,
        suffix,
        workflow_template_path=workflow_template_path,
        workflow_version_template_path=workflow_version_template_path,
        display_name=workflow_display_name_from_path(ctx.path),
    )
    wf_name = f"{workflow_base}.{suffix}.Workflow.yaml"
    wv_name = f"{workflow_base}.{suffix}.WorkflowVersion.yaml"
    for path, exp in (
        (scope_dir / wf_name, exp_wf),
        (scope_dir / wv_name, exp_wv),
    ):
        if not path.is_file():
            raise SystemExit(
                f"Missing {path.relative_to(module_root)} for scope_build_mode=full. "
                f"Run:\n  python {module_root / 'scripts' / 'build_scopes.py'}"
            )
        body = strip_leading_comments_and_blanks(path.read_text(encoding="utf-8"))
        try:
            got = yaml.safe_load(body)
        except yaml.YAMLError as e:
            raise SystemExit(f"Invalid YAML in {path}: {e}") from e
        if got != exp:
            raise SystemExit(
                f"{path} is out of date vs templates. Run:\n"
                f"  python {module_root / 'scripts' / 'build_scopes.py'} --force"
            )


def verify_all_scoped_workflow_bundles(
    module_root: Path,
    contexts: Sequence[ScopeBuildContext],
    workflow_base: str,
    *,
    workflow_template_path: Path | None,
    workflow_version_template_path: Path | None,
) -> None:
    for ctx in contexts:
        verify_scoped_workflow_bundle(
            module_root,
            workflow_base,
            ctx,
            workflow_template_path=workflow_template_path,
            workflow_version_template_path=workflow_version_template_path,
        )
