"""Emit one ``workflows/key_extraction_aliasing.<scope>.WorkflowTrigger.yaml`` per leaf scope."""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any, List, Sequence

import yaml

from scope_build.context import ScopeBuildContext
from scope_build.naming import cdf_external_id_suffix
from scope_build.scope_document_patch import prepare_scope_document_for_context

logger = logging.getLogger(__name__)

# Legacy monolithic output (removed when running build).
LEGACY_MONOLITHIC_NAME = "key_extraction_aliasing_scope_triggers.WorkflowTrigger.yaml"
# Generated per leaf: key_extraction_aliasing.<suffix>.WorkflowTrigger.yaml
GENERATED_TRIGGER_GLOB = "key_extraction_aliasing.*.WorkflowTrigger.yaml"

PLACEHOLDER = "__KEA_CDF_SUFFIX__"
# Safe margin under Cognite task I/O 0.2 MiB (minified JSON byte length).
MAX_SCOPE_DOCUMENT_JSON_BYTES = 200_000
DEFAULT_TRIGGER_TEMPLATE_REL = (
    Path("workflows")
    / "_template"
    / "workflow.template.WorkflowTrigger.yaml.template"
)
DEFAULT_SCOPE_DOCUMENT_REL = Path("workflows") / "_template" / "workflow.template.config.yaml"


def workflow_trigger_filename(suffix: str) -> str:
    """Toolkit filename for one schedule trigger (suffix from ``cdf_external_id_suffix``)."""
    return f"key_extraction_aliasing.{suffix}.WorkflowTrigger.yaml"


def _cleanup_legacy_trigger_layout(workflows_dir: Path) -> None:
    """Remove superseded trigger layouts only (does not delete current dot-form per-scope files).

    Per-scope files ``key_extraction_aliasing.<suffix>.WorkflowTrigger.yaml`` are always
    left on disk even when no longer in the configured ``scope_hierarchy.locations`` tree — remove those by hand if needed.
    """
    legacy = workflows_dir / LEGACY_MONOLITHIC_NAME
    if legacy.is_file():
        legacy.unlink()
        logger.info("Removed legacy monolithic triggers file %s", legacy)
    # Previous layout: <prefix>_<suffix>.WorkflowTrigger.yaml (underscore before scope)
    for pattern in (
        "key_extraction_aliasing_*.WorkflowTrigger.yaml",
        "cdf_key_extraction_aliasing_*.WorkflowTrigger.yaml",
    ):
        for p in sorted(workflows_dir.glob(pattern)):
            p.unlink()
            logger.info("Removed old-format trigger file %s", p.name)


def minified_json_utf8_length(obj: Any) -> int:
    """UTF-8 byte length of JSON with no unnecessary whitespace (platform limit checks)."""
    return len(
        json.dumps(
            obj,
            separators=(",", ":"),
            ensure_ascii=False,
        ).encode("utf-8")
    )


def _assert_scope_document_within_limit(scope_document: dict, *, scope_id: str) -> None:
    n = minified_json_utf8_length(scope_document)
    if n > MAX_SCOPE_DOCUMENT_JSON_BYTES:
        raise ValueError(
            f"scope_document for scope_id={scope_id!r} minified JSON is {n} bytes "
            f"(limit {MAX_SCOPE_DOCUMENT_JSON_BYTES}); shrink config or split scopes."
        )


class WorkflowTriggersBuilder:
    name = "workflow_triggers"

    def __init__(
        self,
        *,
        template_path: Path | None = None,
        scope_document_path: Path | None = None,
    ) -> None:
        self._template_path_override = template_path
        self._scope_document_path_override = scope_document_path

    def run(self, ctx: ScopeBuildContext) -> None:
        """Per-scope no-op; triggers are created if missing in ``write_all``."""

    def write_all(
        self,
        contexts: Sequence[ScopeBuildContext],
        *,
        dry_run: bool,
        module_root: Path | None = None,
    ) -> list[Path] | None:
        """Create missing ``key_extraction_aliasing.<scope>.WorkflowTrigger.yaml`` under ``workflows/``.

        Existing files are not overwritten. Returns paths that were written (or would be written in
        dry-run); returns ``None`` when there are no leaf contexts.
        """
        root = module_root if module_root is not None else (
            contexts[0].module_root if contexts else None
        )
        if not contexts:
            logger.info("No leaf scopes; skip workflow triggers")
            if not dry_run and root is not None:
                _cleanup_legacy_trigger_layout(root / "workflows")
            return None
        module_root = contexts[0].module_root
        workflows_dir = module_root / "workflows"
        template_text = _read_trigger_template(module_root, self._template_path_override)
        scope_tpl = _read_scope_document_template(module_root, self._scope_document_path_override)
        triggers = _render_triggers(template_text, scope_tpl, contexts)
        created: list[Path] = []
        skipped_existing = 0
        header = (
            "# Generated by scripts/build_scopes.py (workflow_triggers builder). "
            "# --build creates this file only if it is missing; delete it to recreate from templates, "
            "or use --check-workflow-triggers in CI to catch drift.\n"
            "# Trigger shell: workflows/_template/workflow.template.WorkflowTrigger.yaml.template\n"
            "# Scope body: workflows/_template/workflow.template.config.yaml\n"
            "# Toolkit substitutes {{ key_extraction_aliasing_schedule }}, {{functionClientId}}, "
            "{{functionClientSecret}}, and {{instance_space}} inside scope_document at deploy time.\n"
        )
        for ctx, trig in zip(contexts, triggers, strict=True):
            suffix = cdf_external_id_suffix(ctx.scope_id)
            out_path = workflows_dir / workflow_trigger_filename(suffix)
            if dry_run:
                if out_path.is_file():
                    skipped_existing += 1
                    logger.info("[dry-run] would skip existing %s", out_path)
                else:
                    created.append(out_path)
                    logger.info("[dry-run] would write %s", out_path)
                continue
            workflows_dir.mkdir(parents=True, exist_ok=True)
            if out_path.is_file():
                skipped_existing += 1
                logger.info("Skipping existing workflow trigger %s", out_path.name)
                continue
            with open(out_path, "w", encoding="utf-8") as f:
                f.write(header)
                yaml.safe_dump(
                    trig,
                    f,
                    default_flow_style=False,
                    allow_unicode=True,
                    sort_keys=False,
                )
            logger.info("Wrote %s", out_path)
            created.append(out_path)

        if not dry_run:
            _cleanup_legacy_trigger_layout(workflows_dir)

        logger.info(
            "Workflow triggers: created %d, skipped %d existing (under workflows/)",
            len(created),
            skipped_existing,
        )
        return created


def _read_trigger_template(module_root: Path, override: Path | None) -> str:
    path = override if override is not None else (module_root / DEFAULT_TRIGGER_TEMPLATE_REL)
    if not path.is_file():
        raise FileNotFoundError(f"Workflow trigger template not found: {path}")
    return path.read_text(encoding="utf-8")


def _read_scope_document_template(module_root: Path, override: Path | None) -> dict:
    path = override if override is not None else (module_root / DEFAULT_SCOPE_DOCUMENT_REL)
    if not path.is_file():
        raise FileNotFoundError(f"Scope document template not found: {path}")
    doc = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(doc, dict):
        raise ValueError(f"Scope document template root must be a mapping: {path}")
    return doc


def _render_triggers(
    template_text: str,
    scope_template: dict,
    contexts: Sequence[ScopeBuildContext],
) -> list[dict]:
    if PLACEHOLDER not in template_text:
        raise ValueError(
            f"Workflow trigger template must contain placeholder {PLACEHOLDER!r} "
            "(replaced with cdf_external_id_suffix per leaf)."
        )
    out: list[dict] = []
    for ctx in contexts:
        suffix = cdf_external_id_suffix(ctx.scope_id)
        chunk = template_text.replace(PLACEHOLDER, suffix)
        trig = yaml.safe_load(chunk)
        if not isinstance(trig, dict):
            raise ValueError("Workflow trigger template must be a single YAML mapping (one trigger)")
        inp = trig.setdefault("input", {})
        scope_document = prepare_scope_document_for_context(scope_template, ctx)
        _assert_scope_document_within_limit(scope_document, scope_id=ctx.scope_id)
        inp["scope_document"] = scope_document
        out.append(trig)
    return out


def _strip_leading_comments_and_blanks(text: str) -> str:
    lines = text.splitlines()
    while lines and (lines[0].startswith("#") or lines[0].strip() == ""):
        lines.pop(0)
    return "\n".join(lines).lstrip()


def verify_triggers_file(
    module_root: Path,
    contexts: List[ScopeBuildContext],
    *,
    template_path: Path | None = None,
    scope_document_path: Path | None = None,
) -> None:
    """Raise SystemExit(1) if a required trigger is missing, invalid YAML, or out of date.

    Extra ``key_extraction_aliasing.*.WorkflowTrigger.yaml`` files on disk are ignored
    (``--build`` does not remove them).
    """
    workflows_dir = module_root / "workflows"
    legacy = workflows_dir / LEGACY_MONOLITHIC_NAME
    if legacy.is_file():
        raise SystemExit(
            f"Legacy {LEGACY_MONOLITHIC_NAME} is present; run:\n"
            f"  python {module_root / 'scripts' / 'build_scopes.py'}\n"
            "to generate per-scope key_extraction_aliasing.<scope>.WorkflowTrigger.yaml files."
        )
    template_text = _read_trigger_template(module_root, template_path)
    scope_tpl = _read_scope_document_template(module_root, scope_document_path)
    expected_by_name: dict[str, dict] = {}
    for ctx in contexts:
        name = workflow_trigger_filename(cdf_external_id_suffix(ctx.scope_id))
        exp = _render_triggers(template_text, scope_tpl, [ctx])[0]
        expected_by_name[name] = exp

    on_disk = {p.name for p in workflows_dir.glob(GENERATED_TRIGGER_GLOB)}
    expected_names = set(expected_by_name.keys())
    missing = expected_names - on_disk
    if missing:
        raise SystemExit(
            f"Missing workflow trigger file(s) for current hierarchy: {sorted(missing)!r}. "
            f"On disk: {sorted(on_disk)!r}. Run:\n  python {module_root / 'scripts' / 'build_scopes.py'}"
        )

    for name, exp in expected_by_name.items():
        path = workflows_dir / name
        body = _strip_leading_comments_and_blanks(path.read_text(encoding="utf-8"))
        try:
            existing = yaml.safe_load(body)
        except yaml.YAMLError as e:
            raise SystemExit(f"Invalid YAML in {path}: {e}") from e
        if existing != exp:
            raise SystemExit(
                f"{name} is out of date. Run:\n  python {module_root / 'scripts' / 'build_scopes.py'}"
            )
