name: producer_{{location}}_ep_files_{{environment}}
sourceId: {{extractor_group_source_id}}
capabilities:
  - sessionsAcl:
      actions: [CREATE]
      scope:
        all: {}
  - datasetsAcl:
      actions: [READ]
      scope:
        idScope:
          ids: ["{{dataset}}"]
  - filesAcl:
      actions: [READ, WRITE]
      scope:
        datasetScope:
          ids: ["{{dataset}}"]
  - dataModelInstancesAcl:
      actions: [READ, WRITE, WRITE_PROPERTIES]
      scope:
        spaceIdScope:
          spaceIds: ["{{instanceSpace}}"]
  - extractionPipelinesAcl:
      actions: [READ, WRITE]
      scope:
        datasetScope:
          ids: ["{{dataset}}"]
  - extractionConfigsAcl:
      actions: [READ, WRITE]
      scope:
        datasetScope:
          ids: ["{{dataset}}"]
  - extractionRunsAcl:
      actions: [READ, WRITE]
      scope:
        datasetScope:
          ids: ["{{dataset}}"]
