import {
  KeaAliasingNode,
  KeaAliasPersistenceNode,
  KeaWritebackRawNode,
  KeaWritebackDataModelingNode,
  KeaEndNode,
  KeaExtractionNode,
  KeaReferenceIndexNode,
  KeaSourceViewNode,
  KeaStartNode,
  KeaSubflowGraphInNode,
  KeaSubflowGraphOutNode,
  KeaSubflowNode,
  KeaSubgraphNode,
  KeaValidationNode,
  KeaValidationRuleNode,
} from "./keaNodes";

export const KEA_FLOW_NODE_TYPES = {
  keaSubflow: KeaSubflowNode,
  keaSubgraph: KeaSubgraphNode,
  keaSubflowGraphIn: KeaSubflowGraphInNode,
  keaSubflowGraphOut: KeaSubflowGraphOutNode,
  keaStart: KeaStartNode,
  keaEnd: KeaEndNode,
  keaSourceView: KeaSourceViewNode,
  keaExtraction: KeaExtractionNode,
  keaAliasing: KeaAliasingNode,
  keaValidation: KeaValidationNode,
  keaMatchValidationRuleSourceView: KeaValidationRuleNode,
  keaMatchValidationRuleExtraction: KeaValidationRuleNode,
  keaMatchValidationRuleAliasing: KeaValidationRuleNode,
  keaAliasPersistence: KeaAliasPersistenceNode,
  keaWritebackRaw: KeaWritebackRawNode,
  keaWritebackDataModeling: KeaWritebackDataModelingNode,
  keaReferenceIndex: KeaReferenceIndexNode,
};
