name: producer_{{location}}_ep_pi_{{sourceSystem}}_{{environment}}
sourceId: {{extractor_group_source_id}}
capabilities:
  - datasetsAcl:
      actions: [READ]
      scope:
        idScope:
          ids: ["{{dataset}}"]
  - timeSeriesAcl:
      actions: [READ, WRITE]
      scope:
        datasetScope:
          ids: ["{{dataset}}"]
  - dataModelsAcl:
      actions: [READ]
      scope:
        spaceIdScope:
          spaceIds:
            - cdf_cdm
            - cdf_extraction_extensions
  - dataModelInstancesAcl:
      actions: [READ, WRITE, WRITE_PROPERTIES]
      scope:
        spaceIdScope:
          spaceIds: ["{{instanceSpace}}"]
  - dataModelInstancesAcl:
      actions: [READ]
      scope:
        spaceIdScope:
          spaceIds:
            - cdf_cdm_units
  - extractionPipelinesAcl:
      actions: [READ]
      scope:
        datasetScope:
          ids: ["{{dataset}}"]
  - extractionConfigsAcl:
      actions: [READ]
      scope:
        datasetScope:
          ids: ["{{dataset}}"]
  - extractionRunsAcl:
      actions: [WRITE]
      scope:
        datasetScope:
          ids: ["{{dataset}}"]
