#!/usr/bin/env python3
"""
Generate cdf_key_extraction_aliasing_site.WorkflowVersion.yaml from the canonical
cdf_key_extraction_aliasing.WorkflowVersion.yaml.

The site workflow differs only in workflow externalId and per-site task externalIds.
Regenerate after editing the canonical file:

  python modules/accelerators/contextualization/cdf_key_extraction_aliasing/workflows/generate_site_workflow_version.py
"""

from __future__ import annotations

import argparse
from pathlib import Path

WORKFLOWS_DIR = Path(__file__).resolve().parent
CANONICAL = WORKFLOWS_DIR / "cdf_key_extraction_aliasing.WorkflowVersion.yaml"
SITE_OUT = WORKFLOWS_DIR / "cdf_key_extraction_aliasing_site.WorkflowVersion.yaml"

REPLACEMENTS: list[tuple[str, str]] = [
    (
        "workflowExternalId: cdf_key_extraction_aliasing\n",
        "workflowExternalId: cdf_key_extraction_aliasing_{{ site_abbreviation }}\n",
    ),
    (
        "    - externalId: 'fn_dm_key_extraction'\n",
        "    - externalId: 'fn_dm_key_extraction_{{ site_abbreviation }}'\n",
    ),
    (
        "    - externalId: 'fn_dm_aliasing'\n",
        "    - externalId: 'fn_dm_aliasing_{{ site_abbreviation }}'\n",
    ),
    (
        "        - externalId: 'fn_dm_key_extraction'\n",
        "        - externalId: 'fn_dm_key_extraction_{{ site_abbreviation }}'\n",
    ),
    (
        "    - externalId: 'fn_dm_alias_persistence'\n",
        "    - externalId: 'fn_dm_alias_persistence_{{ site_abbreviation }}'\n",
    ),
    (
        "        - externalId: 'fn_dm_aliasing'\n",
        "        - externalId: 'fn_dm_aliasing_{{ site_abbreviation }}'\n",
    ),
]


def generate_site_workflow_text() -> str:
    text = CANONICAL.read_text(encoding="utf-8")
    for old, new in REPLACEMENTS:
        if old not in text:
            raise ValueError(
                f"Expected snippet not found in canonical workflow (update {CANONICAL.name} or {Path(__file__).name}): {old!r}"
            )
        text = text.replace(old, new, 1)
    header = (
        "# Generated by generate_site_workflow_version.py from "
        f"{CANONICAL.name}. Do not edit by hand; edit the canonical file and re-run the script.\n"
    )
    return header + text


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit with code 1 if the generated content differs from the committed site file.",
    )
    args = parser.parse_args()
    generated = generate_site_workflow_text()
    if args.check:
        existing = SITE_OUT.read_text(encoding="utf-8")
        if existing != generated:
            raise SystemExit(
                f"{SITE_OUT.name} is out of date. Run:\n  python {Path(__file__).name}"
            )
        return
    SITE_OUT.write_text(generated, encoding="utf-8")
    print(f"Wrote {SITE_OUT}")


if __name__ == "__main__":
    main()
