space: {{ isaSchemaSpace }}
externalId: ProductDefinition
name: ProductDefinition
description: Definition of the production process and resources (ISA-95 Level 3)
implements:
- space: cdf_cdm
  externalId: CogniteDescribable
  version: v1
  type: view
version: {{ viewVersion }}
properties:
  product_definition_id:
    container:
      space: {{ isaSchemaSpace }}
      externalId: ProductDefinition
      type: container
    containerPropertyIdentifier: product_definition_id
    name: Product Definition ID
    description: >
      Unique identifier for the product definition entity, conforming to ISA-95 Level 3 product 
      definition standards. A product definition represents a definition for product segments 
      and production planning. The product_definition_id serves as the primary key and enables 
      consistent tracking across all manufacturing operations, from definition creation through 
      production to completion. This identifier should align with product planning systems and 
      support integration with product planning and production management platforms. [ISA-95 Level 3]
  version:
    container:
      space: {{ isaSchemaSpace }}
      externalId: ProductDefinition
      type: container
    containerPropertyIdentifier: version
    name: Version
    description: >
      Version of the product definition, typically describing the version's purpose 
      or time period (e.g., "1.0", "1.1", "1.2"). The version follows ISA-95 Level 3 naming conventions and should be 
      descriptive enough for product planners and operators to identify the version's purpose and the version's changes. 
      This version is often used in product planning systems, production planning displays, and operational 
      documentation. [ISA-95 Level 3]
  status:
    container:
      space: {{ isaSchemaSpace }}
      externalId: ProductDefinition
      type: container
    containerPropertyIdentifier: status
    name: Status
    description: >
      Status of the product definition, typically describing the status's purpose and the status's changes.
      The status follows ISA-95 Level 3 naming conventions and should be descriptive enough for product planners and operators to identify the status's purpose and the status's changes. 
      This status is often used in product planning systems, production planning displays, and operational 
      documentation. [ISA-95 Level 3]
  valid_from:
    container:
      space: {{ isaSchemaSpace }}
      externalId: ProductDefinition
      type: container
    containerPropertyIdentifier: valid_from
    name: Valid From
    description: >
      Timestamp indicating when the product definition is valid from, enabling time-based product planning and 
      production planning. The valid_from, combined with valid_to, enables calculation of product definition duration, 
      capacity utilization, and product definition adherence metrics. This timestamp is critical for product 
      planning and production planning optimization. [ISA-95 Level 3]
  valid_to:
    container:
      space: {{ isaSchemaSpace }}
      externalId: ProductDefinition
      type: container
    containerPropertyIdentifier: valid_to
    name: Valid To
    description: >
      Timestamp indicating when the product definition is valid to, enabling time-based product planning and 
      production planning. The valid_to, combined with valid_from, enables calculation of product definition duration, 
      capacity utilization, and product definition adherence metrics. This timestamp is critical for product 
      planning and production planning optimization. [ISA-95 Level 3]
  unit:
    container:
      space: {{ isaSchemaSpace }}
      externalId: ProductDefinition
      type: container
    containerPropertyIdentifier: unit
    name: Unit
    description: >
      Reference to the Unit entity that is defined for this product definition, establishing 
      the relationship between product definitions and equipment units. The unit relationship enables 
      navigation from product definition to unit level, supporting unit-level production planning analysis and 
      production tracking. This relationship is essential for understanding how units are utilized within the product definition. 
      Through the Unit entity, other levels can be accessed.[ISA-95 Level 3, ISA-88]
    source:
      space: {{ isaSchemaSpace }}
      externalId: Unit
      version: {{ viewVersion }}
      type: view
  product_segment:
    container:
      space: {{ isaSchemaSpace }}
      externalId: ProductDefinition
      type: container
    containerPropertyIdentifier: product_segment
    name: Product Segment
    description: >
      Reference to the ProductSegment entity that is defined for this product definition, establishing 
      the relationship between product definitions and product segments. The product_segment relationship enables 
      navigation from product definition to segment level, supporting segment-level scheduling analysis and production tracking. 
      This relationship is essential for understanding how product segments are defined and executed within the product definition. 
      [ISA-95 Level 3]  
    source:
      space: {{ isaSchemaSpace }}
      externalId: ProductSegment
      version: {{ viewVersion }}
      type: view
  product_request:
    container:
      space: {{ isaSchemaSpace }}
      externalId: ProductDefinition
      type: container
    containerPropertyIdentifier: product_request
    name: Product Request
    description: >
      Reference to the ProductRequest entity that is defined for this product definition, establishing 
      the relationship between product definitions and product requests. The product_request relationship enables 
      navigation from product definition to product request level, supporting product request-level production planning analysis and 
      production tracking. This relationship is essential for understanding how product requests are defined and executed within the product definition. 
      [ISA-95 Level 3]
    source:
      space: {{ isaSchemaSpace }}
      externalId: ProductRequest
      version: {{ viewVersion }}
      type: view
  files:
    container:
      space: {{ isaSchemaSpace }}
      externalId: ProductDefinition
      type: container
    containerPropertyIdentifier: files
    name: Files
    description: >
      Collection of document files associated with this product definition, following ISA-95 Level 3 product 
      definition documentation standards. Files may include product specifications, process procedures, 
      engineering drawings, certificates, and other product definition-related documentation. This relationship 
      enables comprehensive product definition documentation management and supports engineering, operations, 
      and production planning activities. Document organization should follow ISA-95 Level 3 document 
      classification and naming conventions. [ISA-95 Level 3]
    source:
      space: {{ isaSchemaSpace }}
      externalId: ISAFile
      version: {{ viewVersion }}
      type: view
      