organization: ORG
function_version: v1.0.0
# Update your location
location_name: Springfield
# specify the name of the source making it possible to identify where the data originates
# from, ex: 'workmate', 'sap', 'oracle',..
# Update SOURCE to your source
source_name: springfield
dbName: db_asset_entity_matching
contextualizationId: entity_matcher
contextualizationName: Entity Matcher
schemaSpace: cdf_cdm
viewVersion: v1
assetInstanceSpace: inst_location
timeseriesInstanceSpace: inst_location
functionSpace: sp_entity_matching_fn # space where function code nodes are stored — created by this module
AssetViewExternalId: CogniteAsset
TimeSeriesViewExternalId: CogniteTimeSeries
targetViewExternalId: CogniteAsset
entityViewExternalId: CogniteTimeSeries
targetViewSearchProperty: name
targetViewFilterValues: []
entityViewSearchProperty: name
entityViewFilterValues: []

workflow: EntityMatching
### UPDATE THE FOLLOWING VALUES FOR YOUR IDP CONFIGURATION ###
workflowClientId: ${IDP_CLIENT_ID}
workflowClientSecret: ${IDP_CLIENT_SECRET}
# Update GROUP_SOURCE_ID to your group source ID
entity_matching_processing_group_source_id: ${GROUP_SOURCE_ID}
