# -*- coding: utf-8 -*-
"""
Contextualization Quality Dashboard

Displays metrics from the pre-computed Cognite File generated by the
Contextualization Quality Metrics Cognite Function.

Tabs:
- Configuration (configure data model views and trigger function) - FIRST for onboarding
- Asset Hierarchy Quality
- Equipment-Asset Quality  
- Time Series Contextualization
- Maintenance Workflow Quality (RMDM v1)
- File Annotation Quality (CDM CogniteDiagramAnnotation)
- 3D Model Contextualization (CDM Cognite3DObject)
"""

import json
import streamlit as st
from cognite.client import CogniteClient

# Import dashboard modules
from dashboards import (
    render_asset_hierarchy_dashboard,
    render_equipment_dashboard,
    render_time_series_dashboard,
    render_maintenance_dashboard,
    render_file_annotation_dashboard,
    render_3d_model_dashboard,
    render_metadata_sidebar,
    render_configuration_panel,
)


# ----------------------------------------------------
# PAGE CONFIG 
# ----------------------------------------------------
st.set_page_config(
    page_title="Contextualization Quality Dashboard",
    layout="wide",
    page_icon="*"
)

# ----------------------------------------------------
# CONFIGURATION
# ----------------------------------------------------
METRICS_FILE_EXTERNAL_ID = "contextualization_quality_metrics"

# ----------------------------------------------------
# CDF CONNECTION
# ----------------------------------------------------
client = CogniteClient()


# ----------------------------------------------------
# LOAD METRICS FROM COGNITE FILE
# ----------------------------------------------------
@st.cache_data(ttl=300)  # Cache for 5 minutes
def load_metrics_from_file(external_id: str) -> dict:
    """Load pre-computed metrics from Cognite Files."""
    try:
        file_bytes = client.files.download_bytes(external_id=external_id)
        data = json.loads(file_bytes.decode("utf-8"))
        return data
    except Exception as e:
        return None


# ----------------------------------------------------
# MAIN APP EXECUTION
# ----------------------------------------------------
st.title("Contextualization Quality Dashboard")
st.write("Measure and monitor the contextualization quality of your data in CDF.")
st.markdown("---")

# Load metrics from Cognite File (silent - no error message here)
metrics = load_metrics_from_file(METRICS_FILE_EXTERNAL_ID)

# Check if metrics are available to determine tab order and messaging
has_metrics = metrics is not None

# Tab navigation - Configuration FIRST for better onboarding
tab_config, tab_asset, tab_equipment, tab_ts, tab_maintenance, tab_annotation, tab_3d = st.tabs([
    "Configure & Run",
    "Asset Hierarchy",
    "Equipment-Asset",
    "Time Series",
    "Maintenance",
    "File Annotation",
    "3D Model"
])

# Configuration tab - always available
with tab_config:
    render_configuration_panel(client, show_getting_started=not has_metrics)

# Metrics tabs - show content or "run function" message
if not has_metrics:
    no_metrics_message = """
    **No metrics data available yet**
    
    Go to the **Configure & Run** tab to:
    1. Configure your data model views for each dashboard
    2. Run the metrics function
    
    Once the function completes, the metrics will appear here automatically.
    """
    
    with tab_asset:
        st.info(no_metrics_message)
    with tab_equipment:
        st.info(no_metrics_message)
    with tab_ts:
        st.info(no_metrics_message)
    with tab_maintenance:
        st.info(no_metrics_message)
    with tab_annotation:
        st.info(no_metrics_message)
    with tab_3d:
        st.info(no_metrics_message)
else:
    # Render sidebar with metadata
    render_metadata_sidebar(metrics)
    
    with tab_asset:
        render_asset_hierarchy_dashboard(metrics)

    with tab_equipment:
        render_equipment_dashboard(metrics)

    with tab_ts:
        render_time_series_dashboard(metrics)

    with tab_maintenance:
        render_maintenance_dashboard(metrics)

    with tab_annotation:
        render_file_annotation_dashboard(metrics)

    with tab_3d:
        model3d_metrics = metrics.get("model3d_metrics", {})
        render_3d_model_dashboard(model3d_metrics, metrics.get("metadata"))
