externalId: 'ep_ctx_timeseries_{{location_name}}_{{source_name}}_entity_matching'
config:
  parameters:
    debug: True
    runAll: True
    removeOldAssetLinks: True
    rawDb: 'ds_granular_entity_matching_{{location_name}}'
    rawTableState: 'contextualization_state_store'
    rawTableCtxGood: 'contextualization_{{ sourceExternalId }}_{{ targetExternalId }}_good'
    rawTableCtxBad: 'contextualization_{{ sourceExternalId }}_{{ targetExternalId }}_bad'
    rawTableCtxManual: 'contextualization_{{ sourceExternalId }}_{{ targetExternalId }}_manual_input'
    rawTableCtxRule: 'contextualization_{{ sourceExternalId }}_{{ targetExternalId }}_rule_input'
    autoApprovalThreshold: {{ approval_threshold }}
    autoRejectionThreshold: {{}} Minimum threshold basically, just toss it
    blacklist: ???
    autoReferenceCatalogThreshold: {{}}
  data:
    sourceQuery:
      assetView:
        schemaSpace: {{ sourceSchemaSpace }}
        instanceSpace: {{ sourceInstanceSpace }}
        externalId: {{ sourceExternalId }}
        version: {{ sourceVersion }}
        searchProperty: name
      filters:
        - values: [??]
          negate: False
          operator: ??
          targetProperty: tags
        - values: [??]
          negate: True
          operator: ??
          targetProperty: name
    targetQuery:
      entityView:
        schemaSpace: {{ targetSchemaSpace }}
        instanceSpace: {{ targetInstanceSpace }}
        externalId: {{ targetExternalId }}
        version: {{ targetVersion }}
        searchProperty: aliases
      filters:
        - values: [??]
          negate: False
          operator: ??
          targetProperty: bingus
        - values: [??]
          negate: Idk?
          operator: yuh
          targetProperty: blarngus
