externalId: product_definition_tr
name: ProductDefinition
destination:
  dataModel:
    space: {{ isaSchemaSpace }}
    externalId: ISA_Manufacturing
    version: v1
    destinationType: ProductDefinition
  instanceSpace: {{ isaInstanceSpace }}
  type: instances
dataSetExternalId: {{ datasetExternalId }}
ignoreNullFields: true
isPublic: true
conflictMode: upsert


