"""Build wf_discovery_idx_* dataModeling / schedule WorkflowTrigger documents from runtime config."""

from __future__ import annotations

import logging
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml

from inverted_index.cdm_relations import validate_subscription_config, view_external_id
from inverted_index.config_loader import build_runtime_config, load_yaml_config
from inverted_index.dm_query import collect_view_property_paths, top_level_property_names
from inverted_index.source_index import resolve_source_watch_view_keys
from inverted_index.target_driven import batch_scan_top_level_properties, resolve_query_property

logger = logging.getLogger(__name__)

GENERATED_HEADER = (
    "# Generated by scripts/inverted_index_build/workflow_triggers.py — do not edit by hand.\n"
)

WATERMARK_TRIGGER_PATH = "trigger_source_index_watermark.WorkflowTrigger.yaml"

SOURCE_METADATA_TRIGGER_PREFIX = "trigger_source_metadata_"
TARGET_DRIVEN_TRIGGER_PREFIX = "trigger_target_driven_"


class ToolkitPlaceholder:
    """YAML scalar rendered as unquoted ``{{ name }}`` for Cognite Toolkit."""

    def __init__(self, name: str) -> None:
        self.name = name

    def __repr__(self) -> str:
        return f"ToolkitPlaceholder({self.name!r})"


class _NoAliasDumper(yaml.SafeDumper):
    def ignore_aliases(self, data: object) -> bool:
        return True


def _toolkit_placeholder_representer(dumper: yaml.Dumper, data: ToolkitPlaceholder) -> Any:
    return dumper.represent_scalar(
        "tag:yaml.org,2002:str",
        f"{{{{ {data.name} }}}}",
    )


_NoAliasDumper.add_representer(ToolkitPlaceholder, _toolkit_placeholder_representer)


@dataclass(frozen=True)
class WatchSpec:
    view_key: str
    space: str
    external_id: str
    version: str
    properties: tuple[str, ...]


def _view_ref(view_key: str, views: dict) -> dict[str, str]:
    ref = views.get(view_key)
    if not isinstance(ref, dict):
        raise ValueError(
            f"direct_relation_config.views: missing or invalid entry for key {view_key!r}"
        )
    space = str(ref.get("space") or "").strip()
    external_id = str(ref.get("external_id") or "").strip()
    version = str(ref.get("version") or "v1").strip()
    if not space or not external_id:
        raise ValueError(
            f"direct_relation_config.views.{view_key}: space and external_id are required"
        )
    return {"space": space, "external_id": external_id, "version": version}


def _has_data_filter(view_ref: dict[str, str]) -> dict[str, Any]:
    return {
        "type": "view",
        "space": view_ref["space"],
        "externalId": view_ref["external_id"],
        "version": view_ref["version"],
    }


def _source_select(view_ref: dict[str, str], properties: tuple[str, ...]) -> dict[str, Any]:
    return {
        "sources": [
            {
                "source": {
                    "type": "view",
                    "space": view_ref["space"],
                    "externalId": view_ref["external_id"],
                    "version": view_ref["version"],
                },
                "properties": list(properties),
            }
        ]
    }


def source_metadata_trigger_path(view_key: str) -> str:
    return f"{SOURCE_METADATA_TRIGGER_PREFIX}{view_key}.WorkflowTrigger.yaml"


def target_driven_trigger_path(view_key: str) -> str:
    return f"{TARGET_DRIVEN_TRIGGER_PREFIX}{view_key}.WorkflowTrigger.yaml"


def build_data_modeling_query(
    watch_spec: WatchSpec,
    *,
    batch_size_placeholder: str,
) -> dict[str, Any]:
    """Build a single-view dataModelingQuery (CDF requires exactly one select key)."""
    batch = ToolkitPlaceholder(batch_size_placeholder)
    view_ref = {
        "space": watch_spec.space,
        "external_id": watch_spec.external_id,
        "version": watch_spec.version,
    }
    return {
        "with": {
            watch_spec.view_key: {
                "limit": batch,
                "nodes": {"filter": {"hasData": [_has_data_filter(view_ref)]}},
            }
        },
        "select": {watch_spec.view_key: _source_select(view_ref, watch_spec.properties)},
    }


def resolve_watch_specs_for_source_index(runtime: dict[str, Any]) -> list[WatchSpec]:
    index_field_config = runtime.get("index_field_config") or []
    scope_config = runtime.get("scope_config") or {}
    src_cfg = runtime.get("source_index_config") or {}
    dr_cfg = runtime.get("direct_relation_config") or {}
    views = dr_cfg.get("views") or {}

    watch_keys = list(src_cfg.get("watch_view_keys") or [])
    if not watch_keys:
        watch_keys = resolve_source_watch_view_keys(index_field_config, dr_cfg)
    if not watch_keys:
        raise ValueError("source_index: no watch view keys resolved from index_field_config")

    specs: list[WatchSpec] = []
    for key in watch_keys:
        view_ref = _view_ref(key, views)
        ext = view_ref["external_id"]
        if ext not in {str(v.get("view")) for v in index_field_config if v.get("view")}:
            raise ValueError(
                f"source_index watch key {key!r} ({ext}) is not listed in index_field_config"
            )
        paths = collect_view_property_paths(
            view_external_id=ext,
            index_field_config=index_field_config,
            scope_config=scope_config,
        )
        properties = tuple(top_level_property_names(paths) or ["name", "description"])
        specs.append(
            WatchSpec(
                view_key=key,
                space=view_ref["space"],
                external_id=ext,
                version=view_ref["version"],
                properties=properties,
            )
        )
    return specs


def resolve_watch_specs_for_subscription(runtime: dict[str, Any]) -> list[WatchSpec]:
    subscription_cfg = runtime.get("subscription_config") or {}
    target_driven_cfg = runtime.get("target_driven_config") or {}
    dr_cfg = runtime.get("direct_relation_config") or {}
    views = dr_cfg.get("views") or {}

    sub_errors = validate_subscription_config(subscription_cfg, views=views)
    if sub_errors:
        raise ValueError("Invalid subscription config:\n" + "\n".join(f"  - {e}" for e in sub_errors))

    watch_keys = list(subscription_cfg.get("watch_view_keys") or [])
    if not watch_keys:
        raise ValueError("subscription.watch_view_keys must be a non-empty list")

    query_property = resolve_query_property(target_driven_config=target_driven_cfg)
    properties = tuple(
        batch_scan_top_level_properties(query_property, target_driven_cfg)
    )
    specs: list[WatchSpec] = []
    for key in watch_keys:
        view_ref = _view_ref(key, views)
        specs.append(
            WatchSpec(
                view_key=key,
                space=view_ref["space"],
                external_id=view_external_id(views, key) or view_ref["external_id"],
                version=view_ref["version"],
                properties=properties,
            )
        )
    return specs


def _auth_block() -> dict[str, Any]:
    return {
        "clientId": "{{ workflowClientId }}",
        "clientSecret": "{{ workflowClientSecret }}",
    }


def _per_view_trigger_doc(
    *,
    external_id: str,
    watch_spec: WatchSpec,
    batch_size_placeholder: str,
    batch_timeout_placeholder: str,
    workflow_external_id: str,
) -> dict[str, Any]:
    return {
        "externalId": external_id,
        "triggerRule": {
            "triggerType": "dataModeling",
            "batchSize": ToolkitPlaceholder(batch_size_placeholder),
            "batchTimeout": ToolkitPlaceholder(batch_timeout_placeholder),
            "dataModelingQuery": build_data_modeling_query(
                watch_spec,
                batch_size_placeholder=batch_size_placeholder,
            ),
        },
        "workflowExternalId": workflow_external_id,
        "workflowVersion": "v1",
        "authentication": _auth_block(),
    }


def build_source_metadata_trigger_docs(runtime: dict[str, Any]) -> dict[str, dict[str, Any]]:
    watch_specs = resolve_watch_specs_for_source_index(runtime)
    docs: dict[str, dict[str, Any]] = {}
    for spec in watch_specs:
        rel_name = source_metadata_trigger_path(spec.view_key)
        docs[rel_name] = _per_view_trigger_doc(
            external_id=f"wf_discovery_idx_source_metadata_incremental_trigger_{spec.view_key}",
            watch_spec=spec,
            batch_size_placeholder="source_metadata_batch_size",
            batch_timeout_placeholder="source_metadata_batch_timeout",
            workflow_external_id="wf_discovery_idx_source_metadata_incremental",
        )
    return docs


def build_target_driven_trigger_docs(runtime: dict[str, Any]) -> dict[str, dict[str, Any]]:
    watch_specs = resolve_watch_specs_for_subscription(runtime)
    docs: dict[str, dict[str, Any]] = {}
    for spec in watch_specs:
        rel_name = target_driven_trigger_path(spec.view_key)
        docs[rel_name] = _per_view_trigger_doc(
            external_id=f"wf_discovery_idx_target_driven_incremental_trigger_{spec.view_key}",
            watch_spec=spec,
            batch_size_placeholder="subscription_batch_size",
            batch_timeout_placeholder="subscription_batch_timeout",
            workflow_external_id="wf_discovery_idx_target_driven_incremental",
        )
    return docs


def build_watermark_trigger_doc() -> dict[str, Any]:
    return {
        "externalId": "wf_discovery_idx_source_index_watermark_trigger",
        "triggerRule": {
            "triggerType": "schedule",
            "cronExpression": "{{ source_index_watermark_cron }}",
        },
        "workflowExternalId": "wf_discovery_idx_source_index_watermark",
        "workflowVersion": "v1",
        "authentication": _auth_block(),
    }


def build_all_trigger_docs(runtime: dict[str, Any]) -> dict[str, dict[str, Any]]:
    docs: dict[str, dict[str, Any]] = {}
    docs.update(build_source_metadata_trigger_docs(runtime))
    docs.update(build_target_driven_trigger_docs(runtime))
    docs[WATERMARK_TRIGGER_PATH] = build_watermark_trigger_doc()
    return docs


def _stale_trigger_paths(workflows_dir: Path, expected_names: set[str]) -> list[Path]:
    stale: list[Path] = []
    for pattern in (
        f"{SOURCE_METADATA_TRIGGER_PREFIX}*.WorkflowTrigger.yaml",
        f"{TARGET_DRIVEN_TRIGGER_PREFIX}*.WorkflowTrigger.yaml",
    ):
        for path in workflows_dir.glob(pattern):
            if path.name not in expected_names:
                stale.append(path)
    return stale


def dump_trigger_yaml(doc: dict[str, Any]) -> str:
    body = yaml.dump(
        doc,
        Dumper=_NoAliasDumper,
        default_flow_style=False,
        allow_unicode=True,
        sort_keys=False,
    )
    return _normalize_trigger_body(body)


_PLACEHOLDER_QUOTED = re.compile(
    r"""^(\s*)(batchSize|batchTimeout|limit|cronExpression):\s*['"]?\{\{\s*([a-zA-Z_][a-zA-Z0-9_]*)\s*\}\}['"]?\s*$"""
)


def _normalize_trigger_body(body: str) -> str:
    """Match hand-authored Toolkit trigger style (unquoted ``{{ var }}`` scalars)."""
    lines: list[str] = []
    for line in body.splitlines():
        match = _PLACEHOLDER_QUOTED.match(line)
        if match:
            indent, key, name = match.groups()
            lines.append(f"{indent}{key}: {{{{ {name} }}}}")
            continue
        lines.append(line)
    return "\n".join(lines).strip() + "\n"


def render_trigger_file(doc: dict[str, Any]) -> str:
    return GENERATED_HEADER + dump_trigger_yaml(doc)


def _strip_generated_header(text: str) -> str:
    lines = text.splitlines()
    while lines and (not lines[0].strip() or lines[0].startswith("#")):
        lines.pop(0)
    return "\n".join(lines).strip() + "\n"


def canonical_trigger_text(doc: dict[str, Any]) -> str:
    return dump_trigger_yaml(doc)


def load_runtime_from_config(config_path: Path) -> dict[str, Any]:
    yaml_cfg = load_yaml_config(config_path)
    return build_runtime_config(yaml_cfg)


def generate_inverted_index_triggers(
    *,
    config_path: Path,
    workflows_dir: Path,
    overwrite: bool = False,
) -> list[Path]:
    runtime = load_runtime_from_config(config_path)
    docs = build_all_trigger_docs(runtime)
    written: list[Path] = []
    workflows_dir.mkdir(parents=True, exist_ok=True)
    if overwrite:
        for stale_path in _stale_trigger_paths(workflows_dir, set(docs)):
            stale_path.unlink()
            logger.info("Removed stale %s", stale_path.name)
    for rel_name, doc in docs.items():
        out_path = workflows_dir / rel_name
        if out_path.is_file() and not overwrite:
            logger.info("Skipping existing %s (use --force to overwrite)", out_path.name)
            continue
        out_path.write_text(render_trigger_file(doc), encoding="utf-8")
        logger.info("Wrote %s", out_path)
        written.append(out_path)
    return written


def check_inverted_index_triggers(
    *,
    config_path: Path,
    workflows_dir: Path,
) -> list[str]:
    runtime = load_runtime_from_config(config_path)
    expected_docs = build_all_trigger_docs(runtime)
    errors: list[str] = []
    for stale_path in _stale_trigger_paths(workflows_dir, set(expected_docs)):
        errors.append(
            f"{stale_path.name}: stale per-view trigger (run python module.py build "
            "--build-inverted-index-triggers --force)"
        )
    for rel_name, doc in expected_docs.items():
        out_path = workflows_dir / rel_name
        if not out_path.is_file():
            errors.append(f"{rel_name}: missing (run build --build-inverted-index-triggers --force)")
            continue
        expected_text = canonical_trigger_text(doc)
        on_disk_text = _normalize_trigger_body(_strip_generated_header(out_path.read_text(encoding="utf-8")))
        if on_disk_text != expected_text:
            errors.append(
                f"{rel_name}: out of date (run python module.py build "
                "--build-inverted-index-triggers --force)"
            )
    return errors
