- space: APM_Config
  externalId: default-maintain-config
  sources:
    - source:
        space: APM_Config
        externalId: APM_Config
        version: "1"
        type: view
      properties:
        name: Maintain Solution Model
        appDataSpaceId: maintain_solution_model
        appDataSpaceVersion: "v1"
        customerDataSpaceId: maintain_source_data
        customerDataSpaceVersion: "v1"
        isDefault: true
        fieldConfiguration:
          name:
            alias: Activity Title
            uiIcon: WorkOrders
            displayInGantt: true
            approximateDataSize: medium
            displayInSortDropdown: true
          tags:
            alias: Tags
            approximateDataSize: medium
          type:
            alias: Activity Type
            approximateDataSize: small
            displayInSortDropdown: true
          status:
            alias: Status
            uiIcon: StatusCircle
            displayInGantt: true
            approximateDataSize: small
            displayInSortDropdown: true
          endTime:
            alias: End Time
            dateFormat: DD/MM/YYYY HH:mm
            displayInGantt: true
            approximateDataSize: small
            displayInSortDropdown: true
          priority:
            alias: Priority
            uiIcon: Flag
            approximateDataSize: small
            displayInSortDropdown: true
          priorityDescription:
            alias: Priority Level
            approximateDataSize: small
          startTime:
            alias: Start Time
            dateFormat: DD/MM/YYYY HH:mm
            displayInGantt: true
            approximateDataSize: small
            displayInSortDropdown: true
          description:
            alias: Description
            approximateDataSize: large
          mainAsset:
            alias: Primary Asset
            uiIcon: Asset
            isExternalId: true
          asset:
            alias: Asset
            uiIcon: Asset
            isExternalId: true
          assets:
            alias: Assets
            uiIcon: Asset
            isExternalId: true
        featureConfiguration:
          enableCustomLayouts: true
          canvasConfiguration:
            fileTypeMetadataKey: "Type"
          activities:
            overviewCard:
              filters: {}
          viewMappings:
            file:
              type: view
              space: cdf_cdm
              version: v1
              externalId: CogniteFile
            asset:
              type: view
              space: cdf_cdm
              version: v1
              externalId: CogniteAsset
            activity:
              type: view
              space: maintain_source_data
              version: v1
              externalId: SourceMaintenanceOrder
            operation:
              type: view
              space: cdf_idm
              version: v1
              externalId: CogniteOperation
          psnConfiguration:
            disabled: true
          cabinetConfiguration:
            enablePlanAnalysis: true
          timezoneConfiguration:
            startOfWeek: 1
          gridZones2dConfiguration:
            enabled: true
          rootLocationConfigurations:
            - displayName: "{{location_name}}"
              templateAdmins: []
              assetExternalId: "{{location}}_root"
              checklistAdmins: []
              dataFilters:
                files:
                  assetSubtreeExternalIds:
                    - "{{location}}_root"
                assets:
                  assetSubtreeExternalIds:
                    - "{{location}}_root"
                general:
                  assetSubtreeExternalIds:
                    - "{{location}}_root"
                timeseries:
                  assetSubtreeExternalIds:
                    - "{{location}}_root"
              threeDConfiguration: {}
              appDataInstanceSpace: maintain_solution_model
              sourceDataInstanceSpace: maintain_source_data
          subactivitiesConfiguration:
            enabled: true
        rootLocationsConfiguration:
          locations:
            - label: "{{location_name}}"
              value: "{{location}}"
