# used in /data_sets, /data_models, /functions, /extraction_pipelines, and /workflows
annotationDatasetExternalId: ds_file_annotation

# used in /data_models and /extraction_pipelines
annotationStateExternalId: FileAnnotationState
annotationStateSchemaSpace: sp_hdm #NOTE: stands for space helper data model
annotationStateVersion: v1.0.0
patternModeInstanceSpace: sp_dat_pattern_mode_results
patternDetectSink: pattern_detection_sink_node
fileSchemaSpace: <insert>
fileInstanceSpace: <insert>
fileExternalId: <insert>
fileVersion: <insert>

# used in /raw and /extraction_pipelines
rawDb: db_file_annotation
rawTableDocTag: annotation_documents_tags
rawTableDocDoc: annotation_documents_docs
rawTableDocPattern: annotation_documents_patterns
rawTableCache: annotation_entities_cache
rawManualPatternsCatalog: manual_patterns_catalog
rawTablePromoteCache: annotation_tags_cache

# used in /extraction_pipelines
extractionPipelineExternalId: ep_file_annotation
targetEntitySchemaSpace: <insert>
targetEntityInstanceSpace: <insert>
targetEntityExternalId: <insert>
targetEntityVersion: <insert>

# used in /functions
functionClientId: ${IDP_CLIENT_ID}
functionClientSecret: ${IDP_CLIENT_SECRET}

# used in prepare function
prepareFunctionExternalId: fn_file_annotation_prepare #NOTE: if this is changed, then the folder holding the prepare function must be named the same as the new external ID
prepareFunctionVersion: v1.0.0
prepareWorkflowVersion: v1_prepare
prepareWorkflowTrigger: wf_prepare_trigger

# used in launch function
launchFunctionExternalId: fn_file_annotation_launch #NOTE: if this is changed, then the folder holding the launch function must be named the same as the new external ID
launchFunctionVersion: v1.0.0
launchWorkflowVersion: v1_launch
launchWorkflowTrigger: wf_launch_trigger

# used in finalize function
finalizeFunctionExternalId: fn_file_annotation_finalize #NOTE: if this is changed, then the folder holding the finalize function must be named the same as the new external ID
finalizeFunctionVersion: v1.0.0
finalizeWorkflowVersion: v1_finalize
finalizeWorkflowTrigger: wf_finalize_trigger

# used in promote function
promoteFunctionExternalId: fn_file_annotation_promote #NOTE: if this is changed, then the folder holding the promote function must be named the same as the new external ID
promoteFunctionVersion: v1.0.0
promoteWorkflowVersion: v1_promote
promoteWorkflowTrigger: wf_promote_trigger

# used in /workflows
workflowSchedule: "3-59/10 * * * *" # NOTE: runs every 10 minutes with a 3 minute offset
workflowExternalId: wf_file_annotation

# used in /auth
groupSourceId: <insert> # source ID from Azure AD for the corresponding groups