# used in /data_sets, /data_models, /functions, /extraction_pipelines, and /workflows
contextualizationExtensionsDataSetExternalId: ds_contextualization_extensions

# used in /data_models and /extraction_pipelines
contextualizationExtensionsDataModelExternalId: dm_contextualization_extensions
contextualizationExtensionsDataModelVersion: v1
contextualizationExtensionsSchemaSpace: sp_contextualization_extensions

# Instance spaces
fileInstanceSpace: sp_dat_cdf_contextualized_files # or wherever you'd like to store instances of your file

# Containers
# NOTE: Using camel case because it's more indicative of a class name
annotationStateContainerExternalId: AnnotationState
ocrContainerExternalId: OcrResults
diagramDetectContainerExternalId: DiagramDetectResults
runInformationContainerExternalId: RunInformation

# Views
# NOTE: Using camel case because it's more indicawtive of a class name
contextualizationFileViewExternalId: ContextualizationFile # NOTE: When deployed, the view name will be a concatenation of the following... <organization>FileAnnotation

# organization/name used to extend the CogniteCore views. organization is the standard variable used when creating a quickstart project through toolkit. 
# Take a look at the quickstart config.<env>.yaml file to see example.
# In this template, we'll be extending the extended views from the quickstart module. This enables one instance that populates multiple views/containers such that they can be consumed independetly
organization: <insert>
organizationSchemaSpace: <insert>
organizationDataModelExternalId: <insert>

# used in /raw and /extraction_pipelines
rawDb: db_file_annotation
rawTableDocTag: annotation_documents_tags
rawTableDocDoc: annotation_documents_docs
rawTableCache: annotation_entities_cache

# used in /extraction_pipelines
extractionPipelineExternalId: ep_file_annotation
targetEntitySchemaSpace: <insert>
targetEntityExternalId: <insert>
targetEntityVersion: <insert>

# used in /functions and /workflows
launchFunctionExternalId: fn_file_annotation_launch #NOTE: if this is changed, then the folder holding the launch function must be named the same as the new external ID
launchFunctionVersion: v1.0.0
finalizeFunctionExternalId: fn_file_annotation_finalize #NOTE: if this is changed, then the folder holding the finalize function must be named the same as the new external ID
finalizeFunctionVersion: v1.0.0
functionClientId: ${IDP_CLIENT_ID}
functionClientSecret: ${IDP_CLIENT_SECRET}

# used in /workflows
workflowSchedule: "3-59/10 * * * *" # NOTE: runs every 10 minutes with a 3 minute offset
workflowExternalId: wf_file_annotation
workflowVersion: v1

# used in /auth
groupSourceId: <insert> # source ID from Azure AD for the corresponding groups