[module]
title = "Contextualisation direct relation transformation"
is_selected_by_default = false
id = "dp:acc:ctx:direct_relation_transformation"
package_id = "dp:accelerators"


[dependencies]
modules = []

[[extra_resources]]
location = "accelerators/cdf_common/data_sets/demo.DataSet.yaml"

[[extra_resources]]
location = "accelerators/cdf_common/data_models/demo.Space.yaml"

