"""
build_workflow.py — generates WorkflowVersion.yaml from per-task snippet templates.

Usage:
    python scripts/build_workflow.py            # generate WorkflowVersion.yaml
    python scripts/build_workflow.py --check    # CI mode: exit 1 if output differs from committed file

Reads:
    default.config.yaml                         — enabledSources, dataModelVariant, workflow name
    workflow_template/tasks/*.yaml              — one YAML snippet per task

Writes:
    workflows/wf_ingestion_v1.WorkflowVersion.yaml   (GENERATED — do not edit by hand)
"""

import argparse
import sys
from pathlib import Path

import yaml

# Paths relative to module root
MODULE_ROOT = Path(__file__).parent.parent
CONFIG_FILE = MODULE_ROOT / "default.config.yaml"
TASKS_DIR   = MODULE_ROOT / "workflow_template" / "tasks"
OUTPUT_FILE = MODULE_ROOT / "workflows" / "wf_ingestion_v1.WorkflowVersion.yaml"


def load_config() -> dict:
    return yaml.safe_load(CONFIG_FILE.read_text())


def resolve_task_filenames(config: dict) -> list[str]:
    """
    Return ordered list of task snippet filenames to include, based on
    enabledSources and dataModelVariant flags in default.config.yaml.
    """
    sources = config.get("enabledSources", {})
    ctx     = config.get("enabledContextualization", {})
    dm      = config.get("dataModelVariant", "isa_manufacturing_extension")

    tasks: list[str] = []

    # --- Population phase ---
    if sources.get("pi", False):
        tasks.append("task.pi_timeseries.yaml")

    if sources.get("opcua", False):
        tasks.append("task.opcua_timeseries.yaml")

    if sources.get("sap", False):
        tasks += [
            "task.sap_assets.yaml",
            "task.sap_equipment.yaml",
            "task.sap_maintenance_orders.yaml",
            "task.sap_operations.yaml",
        ]

    # --- Contextualization phase ---
    if dm == "isa_manufacturing_extension":
        if ctx.get("isaRelationships", True) and sources.get("sap", False):
            tasks += [
                "ctx.isa_manufacturing_extension.equipment_to_asset.yaml",
                "ctx.isa_manufacturing_extension.operation_to_order.yaml",
            ]
    else:
        print(f"WARNING: Unknown dataModelVariant '{dm}'. No contextualization tasks added.")
        print("Supported variants: isa_manufacturing_extension | cfihos_oil_and_gas")

    return tasks


def load_tasks(filenames: list[str]) -> list[dict]:
    """Load task snippet YAML files from workflow_template/tasks/ in order."""
    tasks = []
    for fn in filenames:
        path = TASKS_DIR / fn
        if not path.exists():
            print(f"ERROR: Task snippet not found: {path}")
            sys.exit(1)
        tasks.append(yaml.safe_load(path.read_text()))
    return tasks


def validate_dependencies(tasks: list[dict]) -> None:
    """
    Fail loudly if any dependsOn references a task externalId not in the included set.
    Prevents deploying a workflow that references non-existent tasks.
    """
    task_ids = {t["externalId"] for t in tasks}
    for task in tasks:
        for dep in task.get("dependsOn", []):
            dep_id = dep.get("externalId")
            if dep_id and dep_id not in task_ids:
                raise ValueError(
                    f"\nDependency error in task '{task['externalId']}':\n"
                    f"  dependsOn '{dep_id}' which is not in the enabled task set.\n"
                    f"  Included tasks: {sorted(task_ids)}\n"
                    f"  Check enabledSources / enabledContextualization in default.config.yaml."
                )


def build(config: dict) -> str:
    filenames = resolve_task_filenames(config)

    if not filenames:
        print("WARNING: No tasks enabled. Check enabledSources in default.config.yaml.")

    tasks = load_tasks(filenames)
    validate_dependencies(tasks)

    workflow_name = config.get("workflow", "wf_{{location}}_ingestion")

    workflow_version = [
        {
            "workflowExternalId": workflow_name,
            "version": "v1",
            "workflowDefinition": {
                "description": (
                    "GENERATED by scripts/build_workflow.py — do not edit by hand. "
                    f"Enabled sources: {config.get('enabledSources', {})}. "
                    f"DM variant: {config.get('dataModelVariant', 'isa_manufacturing_extension')}."
                ),
                "tasks": tasks,
            },
        }
    ]

    return yaml.dump(workflow_version, sort_keys=False, allow_unicode=True, default_flow_style=False)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="CI mode: exit 1 if generated output differs from committed WorkflowVersion.yaml",
    )
    args = parser.parse_args()

    config    = load_config()
    generated = build(config)

    if args.check:
        if not OUTPUT_FILE.exists():
            print(f"ERROR: {OUTPUT_FILE} does not exist. Run without --check to generate it first.")
            sys.exit(1)
        committed = OUTPUT_FILE.read_text()
        if generated != committed:
            print(
                f"ERROR: {OUTPUT_FILE.name} is out of sync with default.config.yaml.\n"
                "Run `python scripts/build_workflow.py` and commit the result."
            )
            sys.exit(1)
        print(f"OK: {OUTPUT_FILE.name} is up to date.")
    else:
        OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT_FILE.write_text(generated)
        print(f"Written: {OUTPUT_FILE}")
        print(f"Tasks included: {[t['externalId'] for t in yaml.safe_load(generated)[0]['workflowDefinition']['tasks']]}")


if __name__ == "__main__":
    main()
