"""
Generate workflows/wf_ingestion_v1.WorkflowVersion.yaml from config.<env>.yaml
(enabledSources, dataModelVariant) and workflow_template/tasks/. Run after configure_datamodel.py.

Usage: python build_workflow.py [--env dev] [--check]
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml
from _pack_config import (
    find_env_config,
    get_default_env,
    get_ingestion_config,
    load_yaml,
)

MODULE_ROOT = Path(__file__).parent.parent
TASKS_DIR = MODULE_ROOT / "workflow_template" / "tasks"
OUTPUT_FILE = MODULE_ROOT / "workflows" / "wf_ingestion_v1.WorkflowVersion.yaml"


def resolve_task_filenames(config: dict) -> list[str]:
    """
    Return ordered task snippet filenames from ingestion foundation config.
    """
    sources = config.get("enabledSources", {})
    ctx = config.get("enabledContextualization", {})
    dm = config.get("dataModelVariant", "isa_manufacturing_extension")

    tasks: list[str] = []

    if sources.get("pi", False):
        tasks.append("task.pi_timeseries.yaml")

    if sources.get("opcua", False):
        tasks.append("task.opcua_timeseries.yaml")

    if sources.get("sap", False):
        tasks += [
            "task.sap_assets.yaml",
            "task.sap_equipment.yaml",
            "task.sap_maintenance_orders.yaml",
            "task.sap_operations.yaml",
        ]

    if dm == "isa_manufacturing_extension":
        if ctx.get("isaRelationships", True) and sources.get("sap", False):
            tasks += [
                "ctx.isa_manufacturing_extension.equipment_to_asset.yaml",
                "ctx.isa_manufacturing_extension.operation_to_order.yaml",
            ]
    elif dm == "cfihos_oil_and_gas_extension":
        # CFIHOS-specific contextualization task snippets can be added here.
        pass
    else:
        print(f"WARNING: Unknown dataModelVariant '{dm}'. No contextualization tasks added.")
        print(
            "Supported variants: isa_manufacturing_extension | cfihos_oil_and_gas_extension"
        )

    return tasks


def load_tasks(filenames: list[str]) -> list[dict]:
    tasks = []
    for fn in filenames:
        path = TASKS_DIR / fn
        if not path.exists():
            print(f"ERROR: Task snippet not found: {path}")
            sys.exit(1)
        tasks.append(yaml.safe_load(path.read_text()))
    return tasks


def validate_dependencies(tasks: list[dict]) -> None:
    task_ids = {t["externalId"] for t in tasks}
    for task in tasks:
        for dep in task.get("dependsOn", []):
            dep_id = dep.get("externalId")
            if dep_id and dep_id not in task_ids:
                raise ValueError(
                    f"\nDependency error in task '{task['externalId']}':\n"
                    f"  dependsOn '{dep_id}' which is not in the enabled task set.\n"
                    f"  Included tasks: {sorted(task_ids)}\n"
                    f"  Check enabledSources / enabledContextualization in config.<env>.yaml."
                )


def warn_extractor_only_sources(config: dict) -> None:
    """db and files foundations use extractors only — no ingestion workflow tasks."""
    sources = config.get("enabledSources", {})
    for key in ("db", "files"):
        if sources.get(key):
            print(
                f"NOTE: enabledSources.{key}=true — module is deployed via its extractor; "
                "no transformation task is added to wf_ingestion (author transforms separately)."
            )


def build(config: dict, env: str) -> str:
    warn_extractor_only_sources(config)
    filenames = resolve_task_filenames(config)

    if not filenames:
        print(
            f"WARNING: No tasks enabled for env '{env}'. "
            "Check enabledSources in config.<env>.yaml."
        )

    tasks = load_tasks(filenames)
    validate_dependencies(tasks)

    workflow_name = config.get("workflow", "wf_{{location}}_ingestion")

    workflow_version = [
        {
            "workflowExternalId": workflow_name,
            "version": "v1",
            "workflowDefinition": {
                "description": (
                    "GENERATED by scripts/build_workflow.py — do not edit by hand. "
                    f"Env: {env}. "
                    f"Enabled sources: {config.get('enabledSources', {})}. "
                    f"DM variant: {config.get('dataModelVariant', 'isa_manufacturing_extension')}."
                ),
                "tasks": tasks,
            },
        }
    ]

    return yaml.dump(
        workflow_version, sort_keys=False, allow_unicode=True, default_flow_style=False
    )


def load_ingestion_from_env(env: str) -> dict:
    config_path = find_env_config(env)
    if not config_path:
        print(f"ERROR: config.{env}.yaml not found.")
        print("  Run configure_datamodel.py first, or pass --env with an existing config.")
        sys.exit(1)

    config = load_yaml(config_path)
    ingestion = get_ingestion_config(config)
    if not ingestion:
        print(
            f"ERROR: variables.modules.common.cdf_ingestion_foundation "
            f"missing in {config_path.name}.\n"
            "  Run configure_datamodel.py first."
        )
        sys.exit(1)
    return ingestion


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--env",
        default=None,
        help="Environment name (config.<env>.yaml). Defaults to cdf.toml default_env.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="CI mode: exit 1 if generated output differs from committed WorkflowVersion.yaml",
    )
    args = parser.parse_args()

    env = args.env or get_default_env()
    config = load_ingestion_from_env(env)
    generated = build(config, env)

    if args.check:
        if not OUTPUT_FILE.exists():
            print(
                f"ERROR: {OUTPUT_FILE} does not exist. Run without --check to generate it first."
            )
            sys.exit(1)
        committed = OUTPUT_FILE.read_text()
        if generated != committed:
            print(
                f"ERROR: {OUTPUT_FILE.name} is out of sync with config.{env}.yaml.\n"
                "  Run configure_datamodel.py, then python scripts/build_workflow.py"
            )
            sys.exit(1)
        print(f"OK: {OUTPUT_FILE.name} is up to date (env={env}).")
    else:
        OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT_FILE.write_text(generated)
        print(f"Written: {OUTPUT_FILE} (env={env})")
        task_ids = [
            t["externalId"]
            for t in yaml.safe_load(generated)[0]["workflowDefinition"]["tasks"]
        ]
        print(f"Tasks included: {task_ids}")


if __name__ == "__main__":
    main()
