[module]
title = "Ingestion Workflow"
is_selected_by_default = true
id = "dp:acc:ingestion_workflow"
package_id = "dp:accelerators"



[dependencies]
modules = []

[[extra_resources]]
location = "accelerators/cdf_common/data_sets/demo.DataSet.yaml"