location: oslo_refinery # change me
location_name: Oslo Refinery # change me
location_description: Oslo Refinery demo from toolkit # change me
module_version: "1"

# Source IDs from your identity provider for the Infield user groups.
infield_location_read_only_users_source_id: <change_me>
infield_location_normal_users_source_id: <change_me>
infield_location_template_admin_users_source_id: <change_me>
infield_location_checklist_admin_users_source_id: <change_me>
