name: Validate Packages TOML

on:
  pull_request:
    branches: 
    - main
    
  push:

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Validate packages.toml
      run: |
        python validate_packages.py
